# IMPORT Libraries

In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

# LOAD DATASET

In [3]:
df = pd.read_csv("../Data/india_housing_prices.csv")

print("Data loaded successfully")

Data loaded successfully

In [6]:
df.head()

,ID,State,City,Locality,Property_Type,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,...,Age_of_Property,Nearby_Schools,Nearby_Hospitals,Public_Transport_Accessibility,Parking_Space,Security,Amenities,Facing,Owner_Type,Availability_Status
0,1,Tamil Nadu,Chennai,Locality_84,Apartment,1,4740,489.76,0.10,1990,...,35,10,3,High,No,No,"Playground, Gym, Garden, Pool, Clubhouse",West,Owner,Ready_to_Move
1,2,Maharashtra,Pune,Locality_490,Independent House,3,2364,195.52,0.08,2008,...,17,8,1,Low,No,Yes,"Playground, Clubhouse, Pool, Gym, Garden",North,Builder,Under_Construction
2,3,Punjab,Ludhiana,Locality_167,Apartment,2,3642,183.79,0.05,1997,...,28,9,8,Low,Yes,No,"Clubhouse, Pool, Playground, Gym",South,Broker,Ready_to_Move
3,4,Rajasthan,Jodhpur,Locality_393,Independent House,2,2741,300.29,0.11,1991,...,34,5,7,High,Yes,Yes,"Playground, Clubhouse, Gym, Pool, Garden",North,Builder,Ready_to_Move
4,5,Rajasthan,Jaipur,Locality_466,Villa,4,4823,182.90,0.04,2002,...,23,4,9,Low,No,Yes,"Playground, Garden, Gym, Pool, Clubhouse",East,Builder,Ready_to_Move

Dataset Dimensions

In [7]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 250000
Columns: 23

column names

In [8]:
print(df.columns.tolist)

<bound method IndexOpsMixin.tolist of Index(['ID', 'State', 'City', 'Locality', 'Property_Type', 'BHK',
       'Size_in_SqFt', 'Price_in_Lakhs', 'Price_per_SqFt', 'Year_Built',
       'Furnished_Status', 'Floor_No', 'Total_Floors', 'Age_of_Property',
       'Nearby_Schools', 'Nearby_Hospitals', 'Public_Transport_Accessibility',
       'Parking_Space', 'Security', 'Amenities', 'Facing', 'Owner_Type',
       'Availability_Status'],
      dtype='str')>

data types

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 23 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   ID                              250000 non-null  int64
 1   State                           250000 non-null  str
 2   City                            250000 non-null  str
 3   Locality                        250000 non-null  str
 4   Property_Type                   250000 non-null  str
 5   BHK                             250000 non-null  int64
 6   Size_in_SqFt                    250000 non-null  int64
 7   Price_in_Lakhs                  250000 non-null  float64
 8   Price_per_SqFt                  250000 non-null  float64
 9   Year_Built                      250000 non-null  int64
 10  Furnished_Status                250000 non-null  str
 11  Floor_No                        250000 non-null  int64
 12  Total_Floors                    250000 non-null  int64
 13  Age_of_Property                 250000 non-null  int64
 14  Nearby_Schools                  250000 non-null  int64
 15  Nearby_Hospitals                250000 non-null  int64
 16  Public_Transport_Accessibility  250000 non-null  str
 17  Parking_Space                   250000 non-null  str
 18  Security                        250000 non-null  str
 19  Amenities                       250000 non-null  str
 20  Facing                          250000 non-null  str
 21  Owner_Type                      250000 non-null  str
 22  Availability_Status             250000 non-null  str
dtypes: float64(2), int64(9), str(12)
memory usage: 69.7 MB

In [10]:
df.describe()

,ID,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,Floor_No,Total_Floors,Age_of_Property,Nearby_Schools,Nearby_Hospitals
count,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000
mean,125000.500000,2.999396,2749.813216,254.586854,0.130597,2006.520012,14.966800,15.503004,18.479988,5.499860,5.498016
std,72168.927986,1.415521,1300.606954,141.349921,0.130747,9.808575,8.948047,8.671618,9.808575,2.878639,2.871860
min,1.000000,1.000000,500.000000,10.000000,0.000000,1990.000000,0.000000,1.000000,2.000000,1.000000,1.000000
25%,62500.750000,2.000000,1623.000000,132.550000,0.050000,1998.000000,7.000000,8.000000,10.000000,3.000000,3.000000
50%,125000.500000,3.000000,2747.000000,253.870000,0.090000,2007.000000,15.000000,15.000000,18.000000,5.000000,5.000000
75%,187500.250000,4.000000,3874.000000,376.880000,0.160000,2015.000000,23.000000,23.000000,27.000000,8.000000,8.000000
max,250000.000000,5.000000,5000.000000,500.000000,0.990000,2023.000000,30.000000,30.000000,35.000000,10.000000,10.000000

Missing values

In [15]:
missing_values = df.isnull().sum()

print(missing_values)

missing_values = df.isnull().sum()

print(missing_values)
print("Total missing values:", missing_values.sum())

ID                                0
State                             0
City                              0
Locality                          0
Property_Type                     0
BHK                               0
Size_in_SqFt                      0
Price_in_Lakhs                    0
Price_per_SqFt                    0
Year_Built                        0
Furnished_Status                  0
Floor_No                          0
Total_Floors                      0
Age_of_Property                   0
Nearby_Schools                    0
Nearby_Hospitals                  0
Public_Transport_Accessibility    0
Parking_Space                     0
Security                          0
Amenities                         0
Facing                            0
Owner_Type                        0
Availability_Status               0
dtype: int64
ID                                0
State                             0
City                              0
Locality                          0
Property_Type                     0
BHK                               0
Size_in_SqFt                      0
Price_in_Lakhs                    0
Price_per_SqFt                    0
Year_Built                        0
Furnished_Status                  0
Floor_No                          0
Total_Floors                      0
Age_of_Property                   0
Nearby_Schools                    0
Nearby_Hospitals                  0
Public_Transport_Accessibility    0
Parking_Space                     0
Security                          0
Amenities                         0
Facing                            0
Owner_Type                        0
Availability_Status               0
dtype: int64
Total missing values: 0

Duplicate records

In [17]:
print("Duplicated Rows : " , df.duplicated().sum())
print("Duplicated columns : " , df["ID"].duplicated().sum())

Duplicated Rows :  0
Duplicated columns :  0

Unique Values

In [21]:
for col in df.select_dtypes(include="object").columns:
    print("\nColumn:", col)
    print(df[col].unique()[:20])

Column: State
<ArrowStringArray>
[    'Tamil Nadu',    'Maharashtra',         'Punjab',      'Rajasthan',
    'West Bengal',   'Chhattisgarh',          'Delhi',      'Jharkhand',
      'Telangana',      'Karnataka',  'Uttar Pradesh',          'Assam',
    'Uttarakhand',          'Bihar',        'Gujarat',        'Haryana',
 'Andhra Pradesh', 'Madhya Pradesh',         'Kerala',         'Odisha']
Length: 20, dtype: str

Column: City
<ArrowStringArray>
[   'Chennai',       'Pune',   'Ludhiana',    'Jodhpur',     'Jaipur',
   'Durgapur', 'Coimbatore',   'Bilaspur',  'New Delhi',     'Ranchi',
   'Warangal',  'Bangalore',     'Nagpur',    'Lucknow',    'Silchar',
   'Dehradun',      'Noida',       'Gaya', 'Jamshedpur',  'Ahmedabad']
Length: 20, dtype: str

Column: Locality
<ArrowStringArray>
[ 'Locality_84', 'Locality_490', 'Locality_167', 'Locality_393',
 'Locality_466', 'Locality_246', 'Locality_254', 'Locality_232',
 'Locality_122',  'Locality_75', 'Locality_462', 'Locality_227',
 'Locality_287', 'Locality_148', 'Locality_369', 'Locality_265',
  'Locality_50', 'Locality_385', 'Locality_241', 'Locality_286']
Length: 20, dtype: str

Column: Property_Type
<ArrowStringArray>
['Apartment', 'Independent House', 'Villa']
Length: 3, dtype: str

Column: Furnished_Status
<ArrowStringArray>
['Furnished', 'Unfurnished', 'Semi-furnished']
Length: 3, dtype: str

Column: Public_Transport_Accessibility
<ArrowStringArray>
['High', 'Low', 'Medium']
Length: 3, dtype: str

Column: Parking_Space
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

Column: Security
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

Column: Amenities
<ArrowStringArray>
['Playground, Gym, Garden, Pool, Clubhouse',
 'Playground, Clubhouse, Pool, Gym, Garden',
         'Clubhouse, Pool, Playground, Gym',
 'Playground, Clubhouse, Gym, Pool, Garden',
 'Playground, Garden, Gym, Pool, Clubhouse',
                    'Playground, Clubhouse',
            'Clubhouse, Garden, Playground',
         'Gym, Pool, Clubhouse, Playground',
            'Garden, Clubhouse, Playground',
       'Clubhouse, Playground, Garden, Gym',
                                'Clubhouse',
         'Clubhouse, Gym, Playground, Pool',
 'Clubhouse, Garden, Gym, Playground, Pool',
                  'Garden, Gym, Playground',
                               'Playground',
            'Pool, Playground, Garden, Gym',
                     'Pool, Clubhouse, Gym',
 'Garden, Clubhouse, Pool, Gym, Playground',
              'Pool, Playground, Clubhouse',
 'Clubhouse, Gym, Garden, Pool, Playground']
Length: 20, dtype: str

Column: Facing
<ArrowStringArray>
['West', 'North', 'South', 'East']
Length: 4, dtype: str

Column: Owner_Type
<ArrowStringArray>
['Owner', 'Builder', 'Broker']
Length: 3, dtype: str

Column: Availability_Status
<ArrowStringArray>
['Ready_to_Move', 'Under_Construction']
Length: 2, dtype: str

C:\Users\shakti\AppData\Local\Temp\ipykernel_18160\1587067301.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/dev/user_guide/migration.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object").columns:

In [23]:
print(df.describe())

                  ID            BHK   Size_in_SqFt  Price_in_Lakhs  \
count  250000.000000  250000.000000  250000.000000   250000.000000
mean   125000.500000       2.999396    2749.813216      254.586854
std     72168.927986       1.415521    1300.606954      141.349921
min         1.000000       1.000000     500.000000       10.000000
25%     62500.750000       2.000000    1623.000000      132.550000
50%    125000.500000       3.000000    2747.000000      253.870000
75%    187500.250000       4.000000    3874.000000      376.880000
max    250000.000000       5.000000    5000.000000      500.000000

       Price_per_SqFt     Year_Built       Floor_No   Total_Floors  \
count   250000.000000  250000.000000  250000.000000  250000.000000
mean         0.130597    2006.520012      14.966800      15.503004
std          0.130747       9.808575       8.948047       8.671618
min          0.000000    1990.000000       0.000000       1.000000
25%          0.050000    1998.000000       7.000000       8.000000
50%          0.090000    2007.000000      15.000000      15.000000
75%          0.160000    2015.000000      23.000000      23.000000
max          0.990000    2023.000000      30.000000      30.000000

       Age_of_Property  Nearby_Schools  Nearby_Hospitals
count    250000.000000   250000.000000     250000.000000
mean         18.479988        5.499860          5.498016
std           9.808575        2.878639          2.871860
min           2.000000        1.000000          1.000000
25%          10.000000        3.000000          3.000000
50%          18.000000        5.000000          5.000000
75%          27.000000        8.000000          8.000000
max          35.000000       10.000000         10.000000

floor-related errors

In [29]:
invalid_Floors = df[df["Floor_No"] > df["Total_Floors"]]

print("Invalid Floor records  : " , len(invalid_Floors)) 

invalid_Floors[["Floor_No","Total_Floors"]].head()

Invalid Floor records  :  116304

   Floor_No  Total_Floors
0        22             1
1        21            20
4         3             2
5        27             1
6        16             5

price and area

In [33]:
invalid_size = df[df["Price_per_SqFt"] <= 0]

invalid_price = df[df["Price_in_Lakhs"] <= 0]

print("Invalid Size : " , len(invalid_size))
print("invalid_Price : " , len(invalid_price))

Invalid Size :  2534
invalid_Price :  0

Check year and age

In [34]:
print("Minimum year:", df["Year_Built"].min())
print("Maximum year:", df["Year_Built"].max())

print("Minimum age:", df["Age_of_Property"].min())
print("Maximum age:", df["Age_of_Property"].max())

Minimum year: 1990
Maximum year: 2023
Minimum age: 2
Maximum age: 35

In [30]:
df.columns

Index(['ID', 'State', 'City', 'Locality', 'Property_Type', 'BHK',
       'Size_in_SqFt', 'Price_in_Lakhs', 'Price_per_SqFt', 'Year_Built',
       'Furnished_Status', 'Floor_No', 'Total_Floors', 'Age_of_Property',
       'Nearby_Schools', 'Nearby_Hospitals', 'Public_Transport_Accessibility',
       'Parking_Space', 'Security', 'Amenities', 'Facing', 'Owner_Type',
       'Availability_Status'],
      dtype='str')

In [36]:
df.info()



df.describe().T



df["Floor_No"].gt(df["Total_Floors"]).sum()



df["Age_of_Property"].value_counts().head()

<class 'pandas.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 24 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   ID                              250000 non-null  int64
 1   State                           250000 non-null  str
 2   City                            250000 non-null  str
 3   Locality                        250000 non-null  str
 4   Property_Type                   250000 non-null  str
 5   BHK                             250000 non-null  int64
 6   Size_in_SqFt                    250000 non-null  int64
 7   Price_in_Lakhs                  250000 non-null  float64
 8   Price_per_SqFt                  250000 non-null  float64
 9   Year_Built                      250000 non-null  int64
 10  Furnished_Status                250000 non-null  str
 11  Floor_No                        250000 non-null  int64
 12  Total_Floors                    250000 non-null  int64
 13  Age_of_Property                 250000 non-null  int64
 14  Nearby_Schools                  250000 non-null  int64
 15  Nearby_Hospitals                250000 non-null  int64
 16  Public_Transport_Accessibility  250000 non-null  str
 17  Parking_Space                   250000 non-null  str
 18  Security                        250000 non-null  str
 19  Amenities                       250000 non-null  str
 20  Facing                          250000 non-null  str
 21  Owner_Type                      250000 non-null  str
 22  Availability_Status             250000 non-null  str
 23  Calculated_Price_Per_SqFt       250000 non-null  float64
dtypes: float64(3), int64(9), str(12)
memory usage: 71.6 MB

Age_of_Property
2     7568
21    7526
10    7487
18    7468
26    7456
Name: count, dtype: int64

# Data Cleaning

In [37]:
# Create a copy of original dataset


df_clean = df.copy()

print("Backup created successfully")
print("Original Records : " , len(df))
print("Working Records : " , len(df_clean))

Backup created successfully
Original Records :  250000
Working Records :  250000

Remove duplicate records

In [38]:
# Check duplicates

print("Before Cleaning : " , len(df_clean))

# Remove duplicate rows


df_clean = df_clean.drop_duplicates()

print("After cleaning:", len(df_clean))

Before Cleaning :  250000
After cleaning: 250000

In [ ]:
# Duplicate IDs

print("Duplicates Ids : " , df_clean["ID"].duplicated().sum() )

# We should not automatically remove duplicate IDs without inspecting them because two records might have different property details.

Duplicates Ids :  0

Handle missing values

In [40]:
# Check missing values
print(df_clean.isnull().sum())

ID                                0
State                             0
City                              0
Locality                          0
Property_Type                     0
BHK                               0
Size_in_SqFt                      0
Price_in_Lakhs                    0
Price_per_SqFt                    0
Year_Built                        0
Furnished_Status                  0
Floor_No                          0
Total_Floors                      0
Age_of_Property                   0
Nearby_Schools                    0
Nearby_Hospitals                  0
Public_Transport_Accessibility    0
Parking_Space                     0
Security                          0
Amenities                         0
Facing                            0
Owner_Type                        0
Availability_Status               0
Calculated_Price_Per_SqFt         0
dtype: int64

In [ ]:
# Numerical columns
num_cols = df_clean.select_dtypes(include=np.number).columns

for col in num_cols:
    df_clean[col] = df_clean[col].fillna(df_clean[col].median())


# Categorical columns
cat_cols = df_clean.select_dtypes(include=["object","str"]).columns

for col in cat_cols:
    if df_clean[col].isnull().any():
        df_clean[col] = df_clean[col].fillna(
            df_clean[col].mode()[0]
        )

In [48]:

print("Total missing values:", df_clean.isnull().sum().sum())

Total missing values: 0

Clean categorical values
Sometimes the same category is written differently, for example:
- Apartment
- apartment
- APARTMENT


These should be treated as the same category.

In [49]:
# Clean text columns
cat_cols = df_clean.select_dtypes(include=["object","str"]).columns

for col in cat_cols:
    df_clean[col] = df_clean[col].str.strip()
    df_clean[col] = df_clean[col].str.title()

print("Categorical values cleaned!")

Categorical values cleaned!

Verify categorical cleaning

In [51]:
for col in cat_cols:
    print("\n", col)
    print(df_clean[col].unique()[:20])

 State
<ArrowStringArray>
[    'Tamil Nadu',    'Maharashtra',         'Punjab',      'Rajasthan',
    'West Bengal',   'Chhattisgarh',          'Delhi',      'Jharkhand',
      'Telangana',      'Karnataka',  'Uttar Pradesh',          'Assam',
    'Uttarakhand',          'Bihar',        'Gujarat',        'Haryana',
 'Andhra Pradesh', 'Madhya Pradesh',         'Kerala',         'Odisha']
Length: 20, dtype: str

 City
<ArrowStringArray>
[   'Chennai',       'Pune',   'Ludhiana',    'Jodhpur',     'Jaipur',
   'Durgapur', 'Coimbatore',   'Bilaspur',  'New Delhi',     'Ranchi',
   'Warangal',  'Bangalore',     'Nagpur',    'Lucknow',    'Silchar',
   'Dehradun',      'Noida',       'Gaya', 'Jamshedpur',  'Ahmedabad']
Length: 20, dtype: str

 Locality
<ArrowStringArray>
[ 'Locality_84', 'Locality_490', 'Locality_167', 'Locality_393',
 'Locality_466', 'Locality_246', 'Locality_254', 'Locality_232',
 'Locality_122',  'Locality_75', 'Locality_462', 'Locality_227',
 'Locality_287', 'Locality_148', 'Locality_369', 'Locality_265',
  'Locality_50', 'Locality_385', 'Locality_241', 'Locality_286']
Length: 20, dtype: str

 Property_Type
<ArrowStringArray>
['Apartment', 'Independent House', 'Villa']
Length: 3, dtype: str

 Furnished_Status
<ArrowStringArray>
['Furnished', 'Unfurnished', 'Semi-Furnished']
Length: 3, dtype: str

 Public_Transport_Accessibility
<ArrowStringArray>
['High', 'Low', 'Medium']
Length: 3, dtype: str

 Parking_Space
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

 Security
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

 Amenities
<ArrowStringArray>
['Playground, Gym, Garden, Pool, Clubhouse',
 'Playground, Clubhouse, Pool, Gym, Garden',
         'Clubhouse, Pool, Playground, Gym',
 'Playground, Clubhouse, Gym, Pool, Garden',
 'Playground, Garden, Gym, Pool, Clubhouse',
                    'Playground, Clubhouse',
            'Clubhouse, Garden, Playground',
         'Gym, Pool, Clubhouse, Playground',
            'Garden, Clubhouse, Playground',
       'Clubhouse, Playground, Garden, Gym',
                                'Clubhouse',
         'Clubhouse, Gym, Playground, Pool',
 'Clubhouse, Garden, Gym, Playground, Pool',
                  'Garden, Gym, Playground',
                               'Playground',
            'Pool, Playground, Garden, Gym',
                     'Pool, Clubhouse, Gym',
 'Garden, Clubhouse, Pool, Gym, Playground',
              'Pool, Playground, Clubhouse',
 'Clubhouse, Gym, Garden, Pool, Playground']
Length: 20, dtype: str

 Facing
<ArrowStringArray>
['West', 'North', 'South', 'East']
Length: 4, dtype: str

 Owner_Type
<ArrowStringArray>
['Owner', 'Builder', 'Broker']
Length: 3, dtype: str

 Availability_Status
<ArrowStringArray>
['Ready_To_Move', 'Under_Construction']
Length: 2, dtype: str

Handle invalid numerical values

In [52]:
# Check invalid property sizes
invalid_size = df_clean[df_clean["Size_in_SqFt"] <= 0]

# Check invalid property prices
invalid_price = df_clean[df_clean["Price_in_Lakhs"] <= 0]

print("Invalid property sizes:", len(invalid_size))
print("Invalid property prices:", len(invalid_price))

Invalid property sizes: 0
Invalid property prices: 0

In [53]:
invalid_bhk = df_clean[df_clean["BHK"] <= 0]

print("Invalid BHK records:", len(invalid_bhk))

Invalid BHK records: 0

In [54]:
invalid_year = df_clean[
    (df_clean["Year_Built"] < 1800) |
    (df_clean["Year_Built"] > 2025)
]

print("Invalid construction years:", len(invalid_year))

Invalid construction years: 0

Fix property age

- Minimum construction year: 1990
- Maximum construction year: 2023
- Minimum age: 2
- Maximum age: 35

This confirms that the original dataset uses 2025 as its reference year.


For consistency with the dataset, we will preserve that reference year rather than silently changing historical values.

In [55]:
df_clean["Age_of_Property"] = (
    2025 - df_clean["Year_Built"]
)

print(df_clean["Age_of_Property"].describe())

count    250000.000000
mean         18.479988
std           9.808575
min           2.000000
25%          10.000000
50%          18.000000
75%          27.000000
max          35.000000
Name: Age_of_Property, dtype: float64

Investigate floor-related issues
This is the biggest issue we found.

Your dataset has 116,304 records where Floor_No is greater than Total_Floors.

In [56]:
print("Floor number distribution:")
print(df_clean["Floor_No"].value_counts().sort_index().head(20))

print("\nTotal floors distribution:")
print(df_clean["Total_Floors"].value_counts().sort_index().head(20))

Floor number distribution:
Floor_No
0     8203
1     8076
2     8125
3     8073
4     7949
5     8174
6     8166
7     8106
8     8149
9     8064
10    7975
11    8041
12    8077
13    7990
14    8108
15    8154
16    8051
17    8197
18    8145
19    7868
Name: count, dtype: int64

Total floors distribution:
Total_Floors
1     8347
2     8380
3     8439
4     8297
5     8501
6     8327
7     8216
8     8301
9     8416
10    8395
11    8135
12    8303
13    8271
14    8367
15    8336
16    8279
17    8251
18    8205
19    8316
20    8414
Name: count, dtype: int64

In [57]:
df_clean["Invalid_Floor_Flag"] = (
    df_clean["Floor_No"] > df_clean["Total_Floors"]
)

print(
    df_clean["Invalid_Floor_Flag"].value_counts()
)

Invalid_Floor_Flag
False    133696
True     116304
Name: count, dtype: int64

Handle Price per SqFt

In [58]:
print(
    "Zero or negative Price_per_SqFt:",
    (df_clean["Price_per_SqFt"] <= 0).sum()
)

print(
    df_clean.loc[
        df_clean["Price_per_SqFt"] <= 0,
        ["Size_in_SqFt", "Price_in_Lakhs", "Price_per_SqFt"]
    ].head(10)
)

Zero or negative Price_per_SqFt: 2534
      Size_in_SqFt  Price_in_Lakhs  Price_per_SqFt
190           4467           11.62             0.0
214           3471           17.01             0.0
272           4497           21.01             0.0
356           3498           12.80             0.0
387           4775           18.34             0.0
551           3438           15.67             0.0
596           4453           18.89             0.0
654           4479           14.73             0.0
1023          2888           10.30             0.0
1133          4718           17.80             0.0

In [59]:
# Now calculate the correct value using property price and size:

df_clean["Calculated_Price_Per_SqFt"] = (
    df_clean["Price_in_Lakhs"] /
    df_clean["Size_in_SqFt"]
)

In [60]:
# Compare the two columns:

print(
    "Maximum difference:",
    (
        df_clean["Price_per_SqFt"] -
        df_clean["Calculated_Price_Per_SqFt"]
    ).abs().max()
)

Maximum difference: 0.0050000000000000044

Detect outliers using IQR
Outliers are unusually high or low values.

For example, most properties might cost between ₹20 lakh and ₹100 lakh, while a few might cost ₹500 lakh.

We will use the IQR method to identify them.

In [62]:
# Function to detect outliers

def detect_outliers(column):

    Q1 = df_clean[column].quantile(0.25)
    Q3 = df_clean[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR

    outliers = df_clean[
        (df_clean[column] < lower_limit) |
        (df_clean[column] > upper_limit)
    ]

    print("Column:", column)
    print("Lower limit:", lower_limit)
    print("Upper limit:", upper_limit)
    print("Outliers:", len(outliers))

    return outliers

In [ ]:
# Now apply it:

price_outliers = detect_outliers("Price_in_Lakhs")

size_outliers = detect_outliers("Size_in_SqFt")

sqft_outliers = detect_outliers("Price_per_SqFt")

Column: Price_in_Lakhs
Lower limit: -233.945
Upper limit: 743.375
Outliers: 0
Column: Size_in_SqFt
Lower limit: -1753.5
Upper limit: 7250.5
Outliers: 0
Column: Price_per_SqFt
Lower limit: -0.115
Upper limit: 0.325
Outliers: 20020

In [65]:
# Save cleaned dataset

df_clean.to_csv(
    "../data/cleaned_housing_data.csv",
    index=False
)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

Final data cleaning report

In [66]:
print("========== DATA CLEANING REPORT ==========")

print("Original records:", len(df))
print("Cleaned records:", len(df_clean))

print(
    "Missing values:",
    df_clean.isnull().sum().sum()
)

print(
    "Duplicate rows:",
    df_clean.duplicated().sum()
)

print(
    "Invalid floor records:",
    df_clean["Invalid_Floor_Flag"].sum()
)

print(
    "Invalid property sizes:",
    (df_clean["Size_in_SqFt"] <= 0).sum()
)

print(
    "Invalid property prices:",
    (df_clean["Price_in_Lakhs"] <= 0).sum()
)

print("==========================================")

========== DATA CLEANING REPORT ==========
Original records: 250000
Cleaned records: 250000
Missing values: 0
Duplicate rows: 0
Invalid floor records: 116304
Invalid property sizes: 0
Invalid property prices: 0
==========================================

In [67]:
# Display invalid floor records

invalid_floors = df_clean[
    df_clean["Floor_No"] > df_clean["Total_Floors"]
]

invalid_floors[
    ["City", "Property_Type", "Floor_No", "Total_Floors"]
].head(15)

          City      Property_Type  Floor_No  Total_Floors
0      Chennai          Apartment        22             1
1         Pune  Independent House        21            20
4       Jaipur              Villa         3             2
5     Durgapur          Apartment        27             1
6   Coimbatore  Independent House        16             5
7     Bilaspur  Independent House        24             4
8    New Delhi              Villa        23            16
12      Nagpur  Independent House         9             1
13   New Delhi  Independent House        13             4
14     Lucknow          Apartment        26            18
16     Silchar              Villa        15            10
17    Dehradun              Villa        14             8
18        Pune              Villa        10             5
21    Bilaspur              Villa        17             7
24        Gaya          Apartment        25             1

In [68]:
print("Price outliers:", len(price_outliers))

print("Size outliers:", len(size_outliers))

print("Price per sqft outliers:", len(sqft_outliers))

Price outliers: 0
Size outliers: 0
Price per sqft outliers: 20020

In [69]:
print(
    "Zero Price per SqFt:",
    (df_clean["Price_per_SqFt"] <= 0).sum()
)

Zero Price per SqFt: 2534