# Mutual Fund Overview & Insights

## 2. Import Libraries

In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

## import dataset

In [3]:
df = pd.read_csv("comprehensive_mutual_funds_data.csv")

In [4]:
df

,scheme_name,min_sip,min_lumpsum,expense_ratio,fund_size_cr,fund_age_yr,fund_manager,sortino,alpha,sd,beta,sharpe,risk_level,amc_name,rating,category,sub_category,returns_1yr,returns_3yr,returns_5yr
0,Aditya Birla SL Active Debt Multi-Mgr FoF-Dir ...,100,100,0.27,10.0,10,Kaustubh Gupta,0.32,2.24,9.39,0.01,0.24,3,Aditya Birla Sun Life Mutual Fund,3,Other,FoFs Domestic,4.0,6.5,6.9
1,Aditya Birla SL Arbitrage Fund,1000,1000,0.36,4288.0,10,Lovelish Solanki,1.33,1.53,0.72,0.56,1.1,1,Aditya Birla Sun Life Mutual Fund,3,Hybrid,Arbitrage Mutual Funds,5.6,4.8,5.5
2,Aditya Birla SL Asset Allocator FoF-Dir Growth,1000,1000,0.53,157.0,10,Vinod Narayan Bhat,3.44,2.67,10.58,0.67,1.42,5,Aditya Birla Sun Life Mutual Fund,3,Other,FoFs Domestic,2.0,18.9,9.7
3,Aditya Birla SL Bal Bhavishya Yojna – Dir Growth,500,1000,0.76,637.0,4,Atul Penkar,2.18,-6.37,14.99,0.85,0.9,6,Aditya Birla Sun Life Mutual Fund,2,Solution Oriented,Childrens Funds,-0.7,17.1,NaN
4,Aditya Birla SL Balanced Advantage Fund,100,100,0.61,6386.0,10,Mohit Sharma,3.69,1.99,10.38,0.68,1.39,6,Aditya Birla Sun Life Mutual Fund,4,Hybrid,Dynamic Asset Allocation or Balanced Advantage,4.5,18.6,9.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
809,UTI-Unit Linked Insurance Plan – Direct,500,15000,0.96,5068.0,10,Amandeep Chopra,2.47,0.92,7.06,0.44,1.29,4,UTI Mutual Fund,0,Hybrid,Dynamic Asset Allocation or Balanced Advantage,-0.7,13.1,6.2
810,UTI-Value Opportunities Fund,500,5000,1.16,6740.0,10,Vetri Subramaniam,3.21,2.73,15.62,0.9,1.48,6,UTI Mutual Fund,4,Equity,Value Funds,1.7,27.2,12.2
811,WhiteOak Capital Liquid Fund,500,500,0.26,197.0,4,Piyush Baranwal,-0.42,0.93,0.39,0.72,-0.07,1,WhiteOak Capital Mutual Fund,1,Debt,Liquid Mutual Funds,5.3,3.8,NaN
812,WhiteOak Capital Overnight Fund,500,500,0.22,14.0,4,Piyush Baranwal,-0.42,0.93,0.39,0.72,-0.07,1,WhiteOak Capital Mutual Fund,1,Debt,Overnight Mutual Funds,1.7,32.4,13.3
813,WhiteOak Capital Ultra Short Term Fund,500,500,0.33,141.0,4,Piyush Baranwal,2.81,1.2,0.72,0.47,0.8,1,WhiteOak Capital Mutual Fund,2,Debt,Ultra Short Duration Funds,5.3,4.5,NaN

## 4. Initial Data Inspection

In [5]:
# Head

df.head()

,scheme_name,min_sip,min_lumpsum,expense_ratio,fund_size_cr,fund_age_yr,fund_manager,sortino,alpha,sd,beta,sharpe,risk_level,amc_name,rating,category,sub_category,returns_1yr,returns_3yr,returns_5yr
0,Aditya Birla SL Active Debt Multi-Mgr FoF-Dir ...,100,100,0.27,10.0,10,Kaustubh Gupta,0.32,2.24,9.39,0.01,0.24,3,Aditya Birla Sun Life Mutual Fund,3,Other,FoFs Domestic,4.0,6.5,6.9
1,Aditya Birla SL Arbitrage Fund,1000,1000,0.36,4288.0,10,Lovelish Solanki,1.33,1.53,0.72,0.56,1.1,1,Aditya Birla Sun Life Mutual Fund,3,Hybrid,Arbitrage Mutual Funds,5.6,4.8,5.5
2,Aditya Birla SL Asset Allocator FoF-Dir Growth,1000,1000,0.53,157.0,10,Vinod Narayan Bhat,3.44,2.67,10.58,0.67,1.42,5,Aditya Birla Sun Life Mutual Fund,3,Other,FoFs Domestic,2.0,18.9,9.7
3,Aditya Birla SL Bal Bhavishya Yojna – Dir Growth,500,1000,0.76,637.0,4,Atul Penkar,2.18,-6.37,14.99,0.85,0.9,6,Aditya Birla Sun Life Mutual Fund,2,Solution Oriented,Childrens Funds,-0.7,17.1,NaN
4,Aditya Birla SL Balanced Advantage Fund,100,100,0.61,6386.0,10,Mohit Sharma,3.69,1.99,10.38,0.68,1.39,6,Aditya Birla Sun Life Mutual Fund,4,Hybrid,Dynamic Asset Allocation or Balanced Advantage,4.5,18.6,9.7

In [6]:
# Tail

df.tail()

,scheme_name,min_sip,min_lumpsum,expense_ratio,fund_size_cr,fund_age_yr,fund_manager,sortino,alpha,sd,beta,sharpe,risk_level,amc_name,rating,category,sub_category,returns_1yr,returns_3yr,returns_5yr
809,UTI-Unit Linked Insurance Plan – Direct,500,15000,0.96,5068.0,10,Amandeep Chopra,2.47,0.92,7.06,0.44,1.29,4,UTI Mutual Fund,0,Hybrid,Dynamic Asset Allocation or Balanced Advantage,-0.7,13.1,6.2
810,UTI-Value Opportunities Fund,500,5000,1.16,6740.0,10,Vetri Subramaniam,3.21,2.73,15.62,0.9,1.48,6,UTI Mutual Fund,4,Equity,Value Funds,1.7,27.2,12.2
811,WhiteOak Capital Liquid Fund,500,500,0.26,197.0,4,Piyush Baranwal,-0.42,0.93,0.39,0.72,-0.07,1,WhiteOak Capital Mutual Fund,1,Debt,Liquid Mutual Funds,5.3,3.8,NaN
812,WhiteOak Capital Overnight Fund,500,500,0.22,14.0,4,Piyush Baranwal,-0.42,0.93,0.39,0.72,-0.07,1,WhiteOak Capital Mutual Fund,1,Debt,Overnight Mutual Funds,1.7,32.4,13.3
813,WhiteOak Capital Ultra Short Term Fund,500,500,0.33,141.0,4,Piyush Baranwal,2.81,1.2,0.72,0.47,0.8,1,WhiteOak Capital Mutual Fund,2,Debt,Ultra Short Duration Funds,5.3,4.5,NaN

In [7]:
# Shape 

rows , columns = df.shape


print("Number of rows:" , rows)

print("Number of columns:" , columns)

Number of rows: 814
Number of columns: 20

In [8]:
# columns names 

df.columns

Index(['scheme_name', 'min_sip', 'min_lumpsum', 'expense_ratio',
       'fund_size_cr', 'fund_age_yr', 'fund_manager', 'sortino', 'alpha', 'sd',
       'beta', 'sharpe', 'risk_level', 'amc_name', 'rating', 'category',
       'sub_category', 'returns_1yr', 'returns_3yr', 'returns_5yr'],
      dtype='object')

In [9]:
# info 

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 814 entries, 0 to 813
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   scheme_name    814 non-null    object
 1   min_sip        814 non-null    int64
 2   min_lumpsum    814 non-null    int64
 3   expense_ratio  814 non-null    float64
 4   fund_size_cr   814 non-null    float64
 5   fund_age_yr    814 non-null    int64
 6   fund_manager   814 non-null    object
 7   sortino        814 non-null    object
 8   alpha          814 non-null    object
 9   sd             814 non-null    object
 10  beta           814 non-null    object
 11  sharpe         814 non-null    object
 12  risk_level     814 non-null    int64
 13  amc_name       814 non-null    object
 14  rating         814 non-null    int64
 15  category       814 non-null    object
 16  sub_category   814 non-null    object
 17  returns_1yr    814 non-null    float64
 18  returns_3yr    793 non-null    float64
 19  returns_5yr    647 non-null    float64
dtypes: float64(5), int64(5), object(10)
memory usage: 127.3+ KB

In [10]:
# describe

df.describe()

,min_sip,min_lumpsum,expense_ratio,fund_size_cr,fund_age_yr,risk_level,rating,returns_1yr,returns_3yr,returns_5yr
count,814.000000,814.000000,814.000000,814.000000,814.000000,814.000000,814.000000,814.000000,793.000000,647.000000
mean,528.500000,3047.468059,0.713231,3812.854214,8.319410,4.400491,2.641278,3.921376,18.525347,9.490726
std,369.184517,2514.619513,0.482161,7181.479475,2.640622,1.814741,1.463476,6.675502,12.108476,3.714015
min,0.000000,0.000000,0.000000,2.380000,1.000000,1.000000,0.000000,-19.700000,3.300000,-4.100000
25%,150.000000,500.000000,0.310000,175.250000,6.000000,3.000000,2.000000,1.500000,6.200000,6.700000
50%,500.000000,5000.000000,0.615000,940.500000,10.000000,6.000000,3.000000,4.400000,18.500000,8.900000
75%,1000.000000,5000.000000,1.030000,3819.000000,10.000000,6.000000,4.000000,5.600000,27.100000,12.200000
max,2000.000000,25000.000000,2.590000,57052.000000,17.000000,6.000000,5.000000,130.800000,71.400000,23.200000

## 5. Data Quality Check

### 5.1 Missing Value Analysis

In [ ]:
# step 1 missing values

df.isnull().sum()

scheme_name        0
min_sip            0
min_lumpsum        0
expense_ratio      0
fund_size_cr       0
fund_age_yr        0
fund_manager       0
sortino            0
alpha              0
sd                 0
beta               0
sharpe             0
risk_level         0
amc_name           0
rating             0
category           0
sub_category       0
returns_1yr        0
returns_3yr       21
returns_5yr      167
dtype: int64

In [ ]:
# step 2 missing values analysis for return_3yr

df[df['returns_3yr'].isnull()][
    ['scheme_name','fund_age_yr','category','sub_category','returns_1yr','returns_3yr','returns_5yr']
]

,scheme_name,fund_age_yr,category,sub_category,returns_1yr,returns_3yr,returns_5yr
61,AXIS Floater Fund,2,Debt,Floater Mutual Funds,5.8,NaN,NaN
104,Baroda BNP Paribas Banking & PSU Bond Fund,2,Debt,Banking and PSU Mutual Funds,2.5,NaN,NaN
125,BHARAT Bond FOF – April 2025 – Direct Growth,3,Other,FoFs Domestic,2.6,NaN,NaN
154,DSP Floater Fund,2,Debt,Floater Mutual Funds,4.4,NaN,NaN
398,Invesco India Medium Duration Fund,2,Debt,Medium Duration Funds,3.5,NaN,NaN
411,ITI Banking & PSU Debt Fund,2,Debt,Banking and PSU Mutual Funds,5.4,NaN,NaN
412,ITI Dynamic Bond Fund,2,Debt,Dynamic Bond,5.7,NaN,NaN
417,ITI Ultra Short Duration Fund,2,Debt,Ultra Short Duration Funds,5.3,NaN,NaN
495,Mahindra Manulife Short Duration Fund,2,Debt,Short Duration Funds,4.4,NaN,NaN
497,Mirae Asset Banking and PSU Debt Fund,3,Debt,Banking and PSU Mutual Funds,3.7,NaN,NaN
499,Mirae Asset Corporate Bond Fund,2,Debt,Corporate Bond Mutual Funds,3.7,NaN,NaN
509,Mirae Asset Money Market Fund,2,Debt,Money Market Funds,5.3,NaN,NaN
514,Mirae Asset Ultra Short Duration Fund,2,Debt,Ultra Short Duration Funds,5.5,NaN,NaN
631,SBI Floating Rate Debt Fund,2,Debt,Floater Mutual Funds,5.0,NaN,NaN
689,Sundaram Large Cap Fund,2,Equity,Large Cap Mutual Funds,0.9,NaN,NaN
720,Tata Floating Rate Fund,2,Debt,Floater Mutual Funds,5.6,NaN,NaN
755,TRUSTMF Banking & PSU Debt Fund,2,Debt,Banking and PSU Mutual Funds,3.0,NaN,NaN
756,TRUSTMF Liquid Fund,2,Debt,Liquid Mutual Funds,5.6,NaN,NaN
757,TRUSTMF Short Term Fund,2,Debt,Short Duration Funds,4.2,NaN,NaN
769,Union Medium Duration Fund,3,Debt,Medium Duration Funds,2.3,NaN,NaN
770,Union Money Market Fund,2,Debt,Money Market Funds,5.4,NaN,NaN

In [ ]:
# step 3 missing values analysis for return_5yr

df[df['returns_5yr'].isnull()][
    ['scheme_name','fund_age_yr','category','sub_category','returns_1yr','returns_3yr','returns_5yr']
]

,scheme_name,fund_age_yr,category,sub_category,returns_1yr,returns_3yr,returns_5yr
3,Aditya Birla SL Bal Bhavishya Yojna – Dir Growth,4,Solution Oriented,Childrens Funds,-0.7,17.1,NaN
38,Aditya Birla SL Overnight Fund,4,Debt,Overnight Mutual Funds,5.4,3.9,NaN
41,Aditya Birla SL Retirement-The 30s Plan-Dir Gr...,4,Solution Oriented,Retirement Funds,0.0,17.9,NaN
42,Aditya Birla SL Retirement-The 40s Plan-Dir Gr...,4,Solution Oriented,Retirement Funds,-0.1,15.0,NaN
43,Aditya Birla SL Retirement-The 50s Plan-Dir Gr...,4,Solution Oriented,Retirement Funds,3.0,4.6,NaN
...,...,...,...,...,...,...,...
784,UTI-Equity Savings Fund,5,Hybrid,Equity Savings Mutual Funds,6.1,14.7,NaN
786,UTI-Floater Fund,4,Debt,Floater Mutual Funds,5.1,5.9,NaN
801,UTI-Nifty Next 50 Index Fund,5,Other,Index Funds,-6.4,22.2,NaN
811,WhiteOak Capital Liquid Fund,4,Debt,Liquid Mutual Funds,5.3,3.8,NaN
813,WhiteOak Capital Ultra Short Term Fund,4,Debt,Ultra Short Duration Funds,5.3,4.5,NaN

In [ ]:
# duplicates

df.duplicated().sum()

np.int64(0)

In [15]:
# Calculate missing percentages

missing_count = df.isnull().sum()

missing_percentage = (missing_count / len(df)) * 100

missing_summary = pd.DataFrame({
    'Missing Values' : missing_count,
    'Missing percentage' : missing_percentage
})

missing_summary[missing_summary['Missing Values'] > 0 ]

             Missing Values  Missing percentage
returns_3yr              21            2.579853
returns_5yr             167           20.515971

In [16]:
#the age of funds with missing 5-year returns

df[df['returns_5yr'].isnull()]['fund_age_yr'].value_counts().sort_index()

fund_age_yr
2    18
3    27
4    86
5    36
Name: count, dtype: int64

In [18]:
df[df['returns_5yr'].isnull()][
    ['fund_age_yr','returns_1yr','returns_3yr']
].describe()

       fund_age_yr  returns_1yr  returns_3yr
count   167.000000   167.000000   146.000000
mean      3.838323     3.229940    17.297260
std       0.887106     4.332679    12.737189
min       2.000000   -13.000000     3.300000
25%       3.000000     1.200000     4.775000
50%       4.000000     4.400000    17.100000
75%       4.000000     5.400000    25.975000
max       5.000000    22.100000    51.800000

### Missing Value Treatment

In [ ]:
# The dataset contains 21 missing values in returns_3yr (2.58%) and
# 167 missing values in returns_5yr (20.52%).

# The missing values are concentrated among relatively young funds.
# Since these funds may not have sufficient historical data to calculate
# 3-year or 5-year returns, the missing values are retained as NaN rather
# than being replaced with zero or an estimated value.

# During analysis, funds will only be included in calculations involving
# a specific return period when the corresponding return data is available.

Step 5.2 — investigation of  the data types

In [ ]:
df[df.duplicated()]

Empty DataFrame
Columns: [scheme_name, min_sip, min_lumpsum, expense_ratio, fund_size_cr, fund_age_yr, fund_manager, sortino, alpha, sd, beta, sharpe, risk_level, amc_name, rating, category, sub_category, returns_1yr, returns_3yr, returns_5yr]
Index: []

In [ ]:
# data types

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 814 entries, 0 to 813
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   scheme_name    814 non-null    object
 1   min_sip        814 non-null    int64
 2   min_lumpsum    814 non-null    int64
 3   expense_ratio  814 non-null    float64
 4   fund_size_cr   814 non-null    float64
 5   fund_age_yr    814 non-null    int64
 6   fund_manager   814 non-null    object
 7   sortino        814 non-null    object
 8   alpha          814 non-null    object
 9   sd             814 non-null    object
 10  beta           814 non-null    object
 11  sharpe         814 non-null    object
 12  risk_level     814 non-null    int64
 13  amc_name       814 non-null    object
 14  rating         814 non-null    int64
 15  category       814 non-null    object
 16  sub_category   814 non-null    object
 17  returns_1yr    814 non-null    float64
 18  returns_3yr    793 non-null    float64
 19  returns_5yr    647 non-null    float64
dtypes: float64(5), int64(5), object(10)
memory usage: 127.3+ KB

In [ ]:
# # Checking the unique values in performance metric columns

for col in ['sortino','alpha','sd','beta','sharpe']:
    print("\n", col)
    print(df[col].unique()[:30])

 sortino
['0.32' '1.33' '3.44' '2.18' '3.69' '2.07' '1.92' '1.42' '2.28' '1.82'
 '2.42' '3.78' '1.78' '2.21' '2.54' '2.55' '3.4' '2.81' '3.24' '3.13'
 '3.82' '3.09' '3.36' '0.98' '1.07' '0.71' '0.88' '3.73' '3.3' '1.28']

 alpha
['2.24' '1.53' '2.67' '-6.37' '1.99' '1.24' '4.46' '-' '2.38' '3.01'
 '9.37' '5.04' '3.02' '-2.06' '1.43' '1.11' '-1.46' '3.73' '-1.14' '1.65'
 '1.94' '1.69' '0.76' '-0.57' '1.09' '3.33' '4.38' '-1.93' '1.49' '-1.7']

 sd
['9.39' '0.72' '10.58' '14.99' '10.38' '25.53' '1.91' '20.18' '1.93' '2.9'
 '21.12' '15.77' '3.22' '17.61' '12.84' '6.83' '16.6' '1.14' '16.09'
 '11.73' '5.49' '8.56' '16.02' '16.64' '13.89' '3.35' '3.29' '14.93'
 '22.52' '13.99']

 beta
['0.01' '0.56' '0.67' '0.85' '0.68' '0.96' '1.78' '-' '0.78' '-0.95'
 '0.83' '0.91' '0.98' '0.99' '1.37' '0.95' '0.8' '0.36' '0.58' '0.97'
 '0.73' '1.51' '0.79' '0.87' '1' '1.12' '0.89' '1.31' '0.43' '0.6']

 sharpe
['0.24' '1.1' '1.42' '0.9' '1.39' '0.97' '1.09' '1.06' '1.35' '1.47'
 '1.53' '1.58' '1.02' '1.16' '1.33' '1.2' '1.27' '1.66' '1.26' '1.4'
 '1.57' '1.44' '0.7' '0.45' '0.57' '0.64' '1.43' '0.81' '1.14' '2.05']

In [20]:
for col in ['sortino','alpha','sd','beta','sharpe']:
    print(col , ":" , df[col].map(type).value_counts())

sortino : sortino
<class 'str'>    814
Name: count, dtype: int64
alpha : alpha
<class 'str'>    814
Name: count, dtype: int64
sd : sd
<class 'str'>    814
Name: count, dtype: int64
beta : beta
<class 'str'>    814
Name: count, dtype: int64
sharpe : sharpe
<class 'str'>    814
Name: count, dtype: int64

## 6. Data Cleaning

In [ ]:
#   remove unnecessary columns
#   convert data types
#   standardize numeric fields
#   check outliers

## 7. Exploratory Data Analysis

## 8. Risk vs Return Analysis

## 9. Fund Scoring / Ranking

## 10. Top 30 Funds

## 11. Key Insights

## 12. Export Clean Dataset