# Mutual Fund Overview & Insights

## 2. Import Libraries

In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

## import dataset

In [3]:
df = pd.read_csv("comprehensive_mutual_funds_data.csv")

In [4]:
df

,scheme_name,min_sip,min_lumpsum,expense_ratio,fund_size_cr,fund_age_yr,fund_manager,sortino,alpha,sd,beta,sharpe,risk_level,amc_name,rating,category,sub_category,returns_1yr,returns_3yr,returns_5yr
0,Aditya Birla SL Active Debt Multi-Mgr FoF-Dir ...,100,100,0.27,10.0,10,Kaustubh Gupta,0.32,2.24,9.39,0.01,0.24,3,Aditya Birla Sun Life Mutual Fund,3,Other,FoFs Domestic,4.0,6.5,6.9
1,Aditya Birla SL Arbitrage Fund,1000,1000,0.36,4288.0,10,Lovelish Solanki,1.33,1.53,0.72,0.56,1.1,1,Aditya Birla Sun Life Mutual Fund,3,Hybrid,Arbitrage Mutual Funds,5.6,4.8,5.5
2,Aditya Birla SL Asset Allocator FoF-Dir Growth,1000,1000,0.53,157.0,10,Vinod Narayan Bhat,3.44,2.67,10.58,0.67,1.42,5,Aditya Birla Sun Life Mutual Fund,3,Other,FoFs Domestic,2.0,18.9,9.7
3,Aditya Birla SL Bal Bhavishya Yojna – Dir Growth,500,1000,0.76,637.0,4,Atul Penkar,2.18,-6.37,14.99,0.85,0.9,6,Aditya Birla Sun Life Mutual Fund,2,Solution Oriented,Childrens Funds,-0.7,17.1,NaN
4,Aditya Birla SL Balanced Advantage Fund,100,100,0.61,6386.0,10,Mohit Sharma,3.69,1.99,10.38,0.68,1.39,6,Aditya Birla Sun Life Mutual Fund,4,Hybrid,Dynamic Asset Allocation or Balanced Advantage,4.5,18.6,9.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
809,UTI-Unit Linked Insurance Plan – Direct,500,15000,0.96,5068.0,10,Amandeep Chopra,2.47,0.92,7.06,0.44,1.29,4,UTI Mutual Fund,0,Hybrid,Dynamic Asset Allocation or Balanced Advantage,-0.7,13.1,6.2
810,UTI-Value Opportunities Fund,500,5000,1.16,6740.0,10,Vetri Subramaniam,3.21,2.73,15.62,0.9,1.48,6,UTI Mutual Fund,4,Equity,Value Funds,1.7,27.2,12.2
811,WhiteOak Capital Liquid Fund,500,500,0.26,197.0,4,Piyush Baranwal,-0.42,0.93,0.39,0.72,-0.07,1,WhiteOak Capital Mutual Fund,1,Debt,Liquid Mutual Funds,5.3,3.8,NaN
812,WhiteOak Capital Overnight Fund,500,500,0.22,14.0,4,Piyush Baranwal,-0.42,0.93,0.39,0.72,-0.07,1,WhiteOak Capital Mutual Fund,1,Debt,Overnight Mutual Funds,1.7,32.4,13.3
813,WhiteOak Capital Ultra Short Term Fund,500,500,0.33,141.0,4,Piyush Baranwal,2.81,1.2,0.72,0.47,0.8,1,WhiteOak Capital Mutual Fund,2,Debt,Ultra Short Duration Funds,5.3,4.5,NaN

## 4. Initial Data Inspection

In [5]:
# Head

df.head()

,scheme_name,min_sip,min_lumpsum,expense_ratio,fund_size_cr,fund_age_yr,fund_manager,sortino,alpha,sd,beta,sharpe,risk_level,amc_name,rating,category,sub_category,returns_1yr,returns_3yr,returns_5yr
0,Aditya Birla SL Active Debt Multi-Mgr FoF-Dir ...,100,100,0.27,10.0,10,Kaustubh Gupta,0.32,2.24,9.39,0.01,0.24,3,Aditya Birla Sun Life Mutual Fund,3,Other,FoFs Domestic,4.0,6.5,6.9
1,Aditya Birla SL Arbitrage Fund,1000,1000,0.36,4288.0,10,Lovelish Solanki,1.33,1.53,0.72,0.56,1.1,1,Aditya Birla Sun Life Mutual Fund,3,Hybrid,Arbitrage Mutual Funds,5.6,4.8,5.5
2,Aditya Birla SL Asset Allocator FoF-Dir Growth,1000,1000,0.53,157.0,10,Vinod Narayan Bhat,3.44,2.67,10.58,0.67,1.42,5,Aditya Birla Sun Life Mutual Fund,3,Other,FoFs Domestic,2.0,18.9,9.7
3,Aditya Birla SL Bal Bhavishya Yojna – Dir Growth,500,1000,0.76,637.0,4,Atul Penkar,2.18,-6.37,14.99,0.85,0.9,6,Aditya Birla Sun Life Mutual Fund,2,Solution Oriented,Childrens Funds,-0.7,17.1,NaN
4,Aditya Birla SL Balanced Advantage Fund,100,100,0.61,6386.0,10,Mohit Sharma,3.69,1.99,10.38,0.68,1.39,6,Aditya Birla Sun Life Mutual Fund,4,Hybrid,Dynamic Asset Allocation or Balanced Advantage,4.5,18.6,9.7

In [6]:
# Tail

df.tail()

,scheme_name,min_sip,min_lumpsum,expense_ratio,fund_size_cr,fund_age_yr,fund_manager,sortino,alpha,sd,beta,sharpe,risk_level,amc_name,rating,category,sub_category,returns_1yr,returns_3yr,returns_5yr
809,UTI-Unit Linked Insurance Plan – Direct,500,15000,0.96,5068.0,10,Amandeep Chopra,2.47,0.92,7.06,0.44,1.29,4,UTI Mutual Fund,0,Hybrid,Dynamic Asset Allocation or Balanced Advantage,-0.7,13.1,6.2
810,UTI-Value Opportunities Fund,500,5000,1.16,6740.0,10,Vetri Subramaniam,3.21,2.73,15.62,0.9,1.48,6,UTI Mutual Fund,4,Equity,Value Funds,1.7,27.2,12.2
811,WhiteOak Capital Liquid Fund,500,500,0.26,197.0,4,Piyush Baranwal,-0.42,0.93,0.39,0.72,-0.07,1,WhiteOak Capital Mutual Fund,1,Debt,Liquid Mutual Funds,5.3,3.8,NaN
812,WhiteOak Capital Overnight Fund,500,500,0.22,14.0,4,Piyush Baranwal,-0.42,0.93,0.39,0.72,-0.07,1,WhiteOak Capital Mutual Fund,1,Debt,Overnight Mutual Funds,1.7,32.4,13.3
813,WhiteOak Capital Ultra Short Term Fund,500,500,0.33,141.0,4,Piyush Baranwal,2.81,1.2,0.72,0.47,0.8,1,WhiteOak Capital Mutual Fund,2,Debt,Ultra Short Duration Funds,5.3,4.5,NaN

In [7]:
# Shape 

rows , columns = df.shape


print("Number of rows:" , rows)

print("Number of columns:" , columns)

Number of rows: 814
Number of columns: 20

In [8]:
# columns names 

df.columns

Index(['scheme_name', 'min_sip', 'min_lumpsum', 'expense_ratio',
       'fund_size_cr', 'fund_age_yr', 'fund_manager', 'sortino', 'alpha', 'sd',
       'beta', 'sharpe', 'risk_level', 'amc_name', 'rating', 'category',
       'sub_category', 'returns_1yr', 'returns_3yr', 'returns_5yr'],
      dtype='object')

In [9]:
# info 

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 814 entries, 0 to 813
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   scheme_name    814 non-null    object
 1   min_sip        814 non-null    int64
 2   min_lumpsum    814 non-null    int64
 3   expense_ratio  814 non-null    float64
 4   fund_size_cr   814 non-null    float64
 5   fund_age_yr    814 non-null    int64
 6   fund_manager   814 non-null    object
 7   sortino        814 non-null    object
 8   alpha          814 non-null    object
 9   sd             814 non-null    object
 10  beta           814 non-null    object
 11  sharpe         814 non-null    object
 12  risk_level     814 non-null    int64
 13  amc_name       814 non-null    object
 14  rating         814 non-null    int64
 15  category       814 non-null    object
 16  sub_category   814 non-null    object
 17  returns_1yr    814 non-null    float64
 18  returns_3yr    793 non-null    float64
 19  returns_5yr    647 non-null    float64
dtypes: float64(5), int64(5), object(10)
memory usage: 127.3+ KB

In [10]:
# describe

df.describe()

,min_sip,min_lumpsum,expense_ratio,fund_size_cr,fund_age_yr,risk_level,rating,returns_1yr,returns_3yr,returns_5yr
count,814.000000,814.000000,814.000000,814.000000,814.000000,814.000000,814.000000,814.000000,793.000000,647.000000
mean,528.500000,3047.468059,0.713231,3812.854214,8.319410,4.400491,2.641278,3.921376,18.525347,9.490726
std,369.184517,2514.619513,0.482161,7181.479475,2.640622,1.814741,1.463476,6.675502,12.108476,3.714015
min,0.000000,0.000000,0.000000,2.380000,1.000000,1.000000,0.000000,-19.700000,3.300000,-4.100000
25%,150.000000,500.000000,0.310000,175.250000,6.000000,3.000000,2.000000,1.500000,6.200000,6.700000
50%,500.000000,5000.000000,0.615000,940.500000,10.000000,6.000000,3.000000,4.400000,18.500000,8.900000
75%,1000.000000,5000.000000,1.030000,3819.000000,10.000000,6.000000,4.000000,5.600000,27.100000,12.200000
max,2000.000000,25000.000000,2.590000,57052.000000,17.000000,6.000000,5.000000,130.800000,71.400000,23.200000

## 5. Data Quality Check

### 5.1 Missing Value Analysis

In [11]:
# step 1 missing values

df.isnull().sum()

scheme_name        0
min_sip            0
min_lumpsum        0
expense_ratio      0
fund_size_cr       0
fund_age_yr        0
fund_manager       0
sortino            0
alpha              0
sd                 0
beta               0
sharpe             0
risk_level         0
amc_name           0
rating             0
category           0
sub_category       0
returns_1yr        0
returns_3yr       21
returns_5yr      167
dtype: int64

In [12]:
# step 2 missing values analysis for return_3yr

df[df['returns_3yr'].isnull()][
    ['scheme_name','fund_age_yr','category','sub_category','returns_1yr','returns_3yr','returns_5yr']
]

,scheme_name,fund_age_yr,category,sub_category,returns_1yr,returns_3yr,returns_5yr
61,AXIS Floater Fund,2,Debt,Floater Mutual Funds,5.8,NaN,NaN
104,Baroda BNP Paribas Banking & PSU Bond Fund,2,Debt,Banking and PSU Mutual Funds,2.5,NaN,NaN
125,BHARAT Bond FOF – April 2025 – Direct Growth,3,Other,FoFs Domestic,2.6,NaN,NaN
154,DSP Floater Fund,2,Debt,Floater Mutual Funds,4.4,NaN,NaN
398,Invesco India Medium Duration Fund,2,Debt,Medium Duration Funds,3.5,NaN,NaN
411,ITI Banking & PSU Debt Fund,2,Debt,Banking and PSU Mutual Funds,5.4,NaN,NaN
412,ITI Dynamic Bond Fund,2,Debt,Dynamic Bond,5.7,NaN,NaN
417,ITI Ultra Short Duration Fund,2,Debt,Ultra Short Duration Funds,5.3,NaN,NaN
495,Mahindra Manulife Short Duration Fund,2,Debt,Short Duration Funds,4.4,NaN,NaN
497,Mirae Asset Banking and PSU Debt Fund,3,Debt,Banking and PSU Mutual Funds,3.7,NaN,NaN
499,Mirae Asset Corporate Bond Fund,2,Debt,Corporate Bond Mutual Funds,3.7,NaN,NaN
509,Mirae Asset Money Market Fund,2,Debt,Money Market Funds,5.3,NaN,NaN
514,Mirae Asset Ultra Short Duration Fund,2,Debt,Ultra Short Duration Funds,5.5,NaN,NaN
631,SBI Floating Rate Debt Fund,2,Debt,Floater Mutual Funds,5.0,NaN,NaN
689,Sundaram Large Cap Fund,2,Equity,Large Cap Mutual Funds,0.9,NaN,NaN
720,Tata Floating Rate Fund,2,Debt,Floater Mutual Funds,5.6,NaN,NaN
755,TRUSTMF Banking & PSU Debt Fund,2,Debt,Banking and PSU Mutual Funds,3.0,NaN,NaN
756,TRUSTMF Liquid Fund,2,Debt,Liquid Mutual Funds,5.6,NaN,NaN
757,TRUSTMF Short Term Fund,2,Debt,Short Duration Funds,4.2,NaN,NaN
769,Union Medium Duration Fund,3,Debt,Medium Duration Funds,2.3,NaN,NaN
770,Union Money Market Fund,2,Debt,Money Market Funds,5.4,NaN,NaN

In [13]:
# step 3 missing values analysis for return_5yr

df[df['returns_5yr'].isnull()][
    ['scheme_name','fund_age_yr','category','sub_category','returns_1yr','returns_3yr','returns_5yr']
]

,scheme_name,fund_age_yr,category,sub_category,returns_1yr,returns_3yr,returns_5yr
3,Aditya Birla SL Bal Bhavishya Yojna – Dir Growth,4,Solution Oriented,Childrens Funds,-0.7,17.1,NaN
38,Aditya Birla SL Overnight Fund,4,Debt,Overnight Mutual Funds,5.4,3.9,NaN
41,Aditya Birla SL Retirement-The 30s Plan-Dir Gr...,4,Solution Oriented,Retirement Funds,0.0,17.9,NaN
42,Aditya Birla SL Retirement-The 40s Plan-Dir Gr...,4,Solution Oriented,Retirement Funds,-0.1,15.0,NaN
43,Aditya Birla SL Retirement-The 50s Plan-Dir Gr...,4,Solution Oriented,Retirement Funds,3.0,4.6,NaN
...,...,...,...,...,...,...,...
784,UTI-Equity Savings Fund,5,Hybrid,Equity Savings Mutual Funds,6.1,14.7,NaN
786,UTI-Floater Fund,4,Debt,Floater Mutual Funds,5.1,5.9,NaN
801,UTI-Nifty Next 50 Index Fund,5,Other,Index Funds,-6.4,22.2,NaN
811,WhiteOak Capital Liquid Fund,4,Debt,Liquid Mutual Funds,5.3,3.8,NaN
813,WhiteOak Capital Ultra Short Term Fund,4,Debt,Ultra Short Duration Funds,5.3,4.5,NaN

In [14]:
# duplicates

df.duplicated().sum()

np.int64(0)

In [15]:
# Calculate missing percentages

missing_count = df.isnull().sum()

missing_percentage = (missing_count / len(df)) * 100

missing_summary = pd.DataFrame({
    'Missing Values' : missing_count,
    'Missing percentage' : missing_percentage
})

missing_summary[missing_summary['Missing Values'] > 0 ]

             Missing Values  Missing percentage
returns_3yr              21            2.579853
returns_5yr             167           20.515971

In [16]:
#the age of funds with missing 5-year returns

df[df['returns_5yr'].isnull()]['fund_age_yr'].value_counts().sort_index()

fund_age_yr
2    18
3    27
4    86
5    36
Name: count, dtype: int64

In [17]:
df[df['returns_5yr'].isnull()][
    ['fund_age_yr','returns_1yr','returns_3yr']
].describe()

       fund_age_yr  returns_1yr  returns_3yr
count   167.000000   167.000000   146.000000
mean      3.838323     3.229940    17.297260
std       0.887106     4.332679    12.737189
min       2.000000   -13.000000     3.300000
25%       3.000000     1.200000     4.775000
50%       4.000000     4.400000    17.100000
75%       4.000000     5.400000    25.975000
max       5.000000    22.100000    51.800000

### Missing Value Treatment

In [18]:
# The dataset contains 21 missing values in returns_3yr (2.58%) and
# 167 missing values in returns_5yr (20.52%).

# The missing values are concentrated among relatively young funds.
# Since these funds may not have sufficient historical data to calculate
# 3-year or 5-year returns, the missing values are retained as NaN rather
# than being replaced with zero or an estimated value.

# During analysis, funds will only be included in calculations involving
# a specific return period when the corresponding return data is available.

Step 5.2 — investigation of  the data types

In [19]:
df[df.duplicated()]

Empty DataFrame
Columns: [scheme_name, min_sip, min_lumpsum, expense_ratio, fund_size_cr, fund_age_yr, fund_manager, sortino, alpha, sd, beta, sharpe, risk_level, amc_name, rating, category, sub_category, returns_1yr, returns_3yr, returns_5yr]
Index: []

In [20]:
# data types

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 814 entries, 0 to 813
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   scheme_name    814 non-null    object
 1   min_sip        814 non-null    int64
 2   min_lumpsum    814 non-null    int64
 3   expense_ratio  814 non-null    float64
 4   fund_size_cr   814 non-null    float64
 5   fund_age_yr    814 non-null    int64
 6   fund_manager   814 non-null    object
 7   sortino        814 non-null    object
 8   alpha          814 non-null    object
 9   sd             814 non-null    object
 10  beta           814 non-null    object
 11  sharpe         814 non-null    object
 12  risk_level     814 non-null    int64
 13  amc_name       814 non-null    object
 14  rating         814 non-null    int64
 15  category       814 non-null    object
 16  sub_category   814 non-null    object
 17  returns_1yr    814 non-null    float64
 18  returns_3yr    793 non-null    float64
 19  returns_5yr    647 non-null    float64
dtypes: float64(5), int64(5), object(10)
memory usage: 127.3+ KB

In [21]:
# # Checking the unique values in performance metric columns

for col in ['sortino','alpha','sd','beta','sharpe']:
    print("\n", col)
    print(df[col].unique()[:30])

 sortino
['0.32' '1.33' '3.44' '2.18' '3.69' '2.07' '1.92' '1.42' '2.28' '1.82'
 '2.42' '3.78' '1.78' '2.21' '2.54' '2.55' '3.4' '2.81' '3.24' '3.13'
 '3.82' '3.09' '3.36' '0.98' '1.07' '0.71' '0.88' '3.73' '3.3' '1.28']

 alpha
['2.24' '1.53' '2.67' '-6.37' '1.99' '1.24' '4.46' '-' '2.38' '3.01'
 '9.37' '5.04' '3.02' '-2.06' '1.43' '1.11' '-1.46' '3.73' '-1.14' '1.65'
 '1.94' '1.69' '0.76' '-0.57' '1.09' '3.33' '4.38' '-1.93' '1.49' '-1.7']

 sd
['9.39' '0.72' '10.58' '14.99' '10.38' '25.53' '1.91' '20.18' '1.93' '2.9'
 '21.12' '15.77' '3.22' '17.61' '12.84' '6.83' '16.6' '1.14' '16.09'
 '11.73' '5.49' '8.56' '16.02' '16.64' '13.89' '3.35' '3.29' '14.93'
 '22.52' '13.99']

 beta
['0.01' '0.56' '0.67' '0.85' '0.68' '0.96' '1.78' '-' '0.78' '-0.95'
 '0.83' '0.91' '0.98' '0.99' '1.37' '0.95' '0.8' '0.36' '0.58' '0.97'
 '0.73' '1.51' '0.79' '0.87' '1' '1.12' '0.89' '1.31' '0.43' '0.6']

 sharpe
['0.24' '1.1' '1.42' '0.9' '1.39' '0.97' '1.09' '1.06' '1.35' '1.47'
 '1.53' '1.58' '1.02' '1.16' '1.33' '1.2' '1.27' '1.66' '1.26' '1.4'
 '1.57' '1.44' '0.7' '0.45' '0.57' '0.64' '1.43' '0.81' '1.14' '2.05']

In [22]:
for col in ['sortino','alpha','sd','beta','sharpe']:
    print(col , ":" , df[col].map(type).value_counts())

sortino : sortino
<class 'str'>    814
Name: count, dtype: int64
alpha : alpha
<class 'str'>    814
Name: count, dtype: int64
sd : sd
<class 'str'>    814
Name: count, dtype: int64
beta : beta
<class 'str'>    814
Name: count, dtype: int64
sharpe : sharpe
<class 'str'>    814
Name: count, dtype: int64

In [23]:
# Checking for non-numeric values

performance_cols = ['sortino', 'alpha', 'sd', 'beta', 'sharpe']

for col in performance_cols:
    numeric_values =  pd.to_numeric(df[col], errors='coerce')

    print(col , "-> Non_numerice values:" , numeric_values.isna().sum())

sortino -> Non_numerice values: 23
alpha -> Non_numerice values: 42
sd -> Non_numerice values: 24
beta -> Non_numerice values: 42
sharpe -> Non_numerice values: 23

In [24]:
# Identify the actual non-numeric values

for col in performance_cols:
    numeric_values = pd.to_numeric(df[col], errors='coerce')
    
    non_numeric = df.loc[numeric_values.isna(), col].unique()
    
    print(f"\n{col}")
    print(non_numeric)

sortino
['-']

alpha
['-']

sd
['-']

beta
['-']

sharpe
['-']

In [25]:
# Replace '-' with NaN and convert performance metrics to numeric

for col in performance_cols:
    df[col] = df[col].replace('-' , np.nan)

    df[col] = pd.to_numeric(df[col], errors='coerce')

In [26]:
df[performance_cols].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 814 entries, 0 to 813
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   sortino  791 non-null    float64
 1   alpha    772 non-null    float64
 2   sd       790 non-null    float64
 3   beta     772 non-null    float64
 4   sharpe   791 non-null    float64
dtypes: float64(5)
memory usage: 31.9 KB

In [27]:
df[performance_cols].isnull().sum()

sortino    23
alpha      42
sd         24
beta       42
sharpe     23
dtype: int64

Step 5.5 — Check categorical consistency

In [28]:
df['category'].value_counts()

category
Equity               308
Debt                 282
Hybrid               116
Other                 80
Solution Oriented     28
Name: count, dtype: int64

In [29]:
df['sub_category'].value_counts()

sub_category
Sectoral / Thematic Mutual Funds                  82
ELSS Mutual Funds                                 52
FoFs Domestic                                     35
Liquid Mutual Funds                               34
Index Funds                                       30
Aggressive Hybrid Mutual Funds                    30
Large Cap Mutual Funds                            28
Overnight Mutual Funds                            26
Small Cap Mutual Funds                            25
Ultra Short Duration Funds                        25
Large & Mid Cap Funds                             24
Mid Cap Mutual Funds                              23
Short Duration Funds                              23
Arbitrage Mutual Funds                            22
Flexi Cap Funds                                   22
Dynamic Bond                                      22
Banking and PSU Mutual Funds                      21
Equity Savings Mutual Funds                       21
Low Duration Funds                                20
Focused Funds                                     20
Retirement Funds                                  20
Gilt Mutual Funds                                 19
Money Market Funds                                19
Corporate Bond Mutual Funds                       19
Dynamic Asset Allocation or Balanced Advantage    19
Conservative Hybrid Mutual Funds                  17
FoFs Overseas                                     15
Medium Duration Funds                             14
Credit Risk Funds                                 14
Value Funds                                       13
Medium to Long Duration Funds                     11
Floater Mutual Funds                              11
Multi Cap Funds                                   10
Childrens Funds                                    8
Multi Asset Allocation Mutual Funds                7
Dividend Yield Funds                               6
Fixed Maturity Plans                               4
Contra Funds                                       3
Name: count, dtype: int64

In [30]:
df['risk_level'].value_counts().sort_index

<bound method Series.sort_index of risk_level
6    418
2    127
3    124
4     65
1     53
5     27
Name: count, dtype: int64>

In [31]:
df['rating'].value_counts().sort_index()

rating
0    108
1     58
2    168
3    243
4    158
5     79
Name: count, dtype: int64

No columns were removed because each field provides either performance, risk, cost, classification, accessibility, or fund-identification information relevant to the analysis.

### Column Relevance Check

No columns were removed because all 20 fields provide relevant information
for the analysis, including fund identification, investment requirements,
cost, fund characteristics, risk metrics, ratings, classification and
historical returns.

## Step 5.6 — Check whether missing performance metrics are concentrated in particular funds

In [32]:

df[performance_cols].isnull().sum(axis=1).value_counts().sort_index()

0    771
1      1
2     19
5     23
Name: count, dtype: int64

In [33]:

df[df[performance_cols].isnull().any(axis=1)][
    ['scheme_name', 'fund_age_yr', 'category'] + performance_cols
].head(20)

,scheme_name,fund_age_yr,category,sortino,alpha,sd,beta,sharpe
7,Aditya Birla SL CEF – Global Agri Plan-Direct ...,10,Equity,1.42,NaN,20.18,NaN,1.06
23,Aditya Birla SL Global Emerging Oppt Fund,10,Other,0.98,NaN,16.64,NaN,0.70
29,Aditya Birla SL Inter Equity – Plan A-Direct G...,10,Equity,1.28,NaN,13.99,NaN,0.81
61,AXIS Floater Fund,2,Debt,NaN,NaN,NaN,NaN,NaN
63,AXIS FTP – Series 104 – 1112Days,4,Debt,7.27,5.29,NaN,2.36,2.19
64,AXIS FTP – Series 109 – 111Days,1,Debt,NaN,NaN,NaN,NaN,NaN
104,Baroda BNP Paribas Banking & PSU Bond Fund,2,Debt,NaN,NaN,NaN,NaN,NaN
125,BHARAT Bond FOF – April 2025 – Direct Growth,3,Other,NaN,NaN,NaN,NaN,NaN
154,DSP Floater Fund,2,Debt,NaN,NaN,NaN,NaN,NaN
156,DSP Global Allocation Fund,9,Other,1.15,NaN,10.88,NaN,0.67
176,DSP US Flexible Equity Fund,10,Other,1.95,NaN,16.40,NaN,1.10
177,DSP World Gold Fund,10,Other,1.11,NaN,36.51,NaN,0.40
178,DSP World Mining Fund,10,Other,1.68,NaN,28.33,NaN,1.08
184,Edelweiss Europe Dynamic Equity Offshore – Dir...,9,Other,1.64,NaN,19.12,NaN,0.93
187,Edelweiss Greater China Equity Off-Shore Fund,10,Other,0.60,NaN,25.75,NaN,0.30
197,Edelweiss US Value Equity Offshore Fund,10,Other,2.17,NaN,16.38,NaN,1.03
207,Franklin India Feeder – Franklin U.S. Opp.-Dir...,10,Other,0.95,NaN,23.08,NaN,0.50
262,HSBC Asia Pacific (Ex Japan) DYF – Direct Growth,9,Other,0.87,NaN,17.08,NaN,0.48
317,ICICI Pru Global Stable Equity Fund,10,Other,1.69,NaN,13.70,NaN,0.90
350,ICICI Pru US Bluechip Equity Fund,10,Equity,1.69,NaN,19.18,NaN,0.88

In [34]:
missing_performance = df[performance_cols].isnull().any(axis=1)

df.loc[missing_performance, 'fund_age_yr'].value_counts().sort_index()

fund_age_yr
1      1
2     17
3      3
4      3
7      1
8      1
9      4
10    13
Name: count, dtype: int64

In [35]:
df.loc[
    missing_performance,
    ['fund_age_yr', 'category']
].value_counts().sort_index()

fund_age_yr  category
1            Debt         1
2            Debt        17
3            Debt         2
             Other        1
4            Debt         1
             Equity       1
             Other        1
7            Equity       1
8            Equity       1
9            Other        4
10           Equity       3
             Other       10
Name: count, dtype: int64

### Missing Value Treatment

The dataset contains missing values in historical return and performance
metric fields. Missing values in `returns_3yr` and `returns_5yr` are retained
because the corresponding historical periods may not be available for all
funds.

The `-` values found in the performance metric columns were treated as
unavailable values and converted to NaN. These missing values were not
replaced with zero because an unavailable metric does not imply a value of
zero.

The missing performance metrics affect only a small portion of the dataset,
so the records are retained and missing values will be handled appropriately
during the ranking and analysis stages.

## Step 5.8 — Numerical consistency check

In [36]:
# Checking the minimum and maximum values of important numerical columns

numeric_cols = [
    'min_sip',
    'min_lumpsum',
    'expense_ratio',
    'fund_size_cr',
    'fund_age_yr',
    'sortino',
    'alpha',
    'sd',
    'beta',
    'sharpe',
    'risk_level',
    'rating',
    'returns_1yr',
    'returns_3yr',
    'returns_5yr'
]

df[numeric_cols].agg(['min', 'max']).T

                 min       max
min_sip         0.00   2000.00
min_lumpsum     0.00  25000.00
expense_ratio   0.00      2.59
fund_size_cr    2.38  57052.00
fund_age_yr     1.00     17.00
sortino        -1.77     12.57
alpha         -13.36     27.24
sd              0.27     77.72
beta          -31.86      5.40
sharpe         -0.82      3.52
risk_level      1.00      6.00
rating          0.00      5.00
returns_1yr   -19.70    130.80
returns_3yr     3.30     71.40
returns_5yr    -4.10     23.20

In [37]:
df[numeric_cols].lt(0).sum()

min_sip            0
min_lumpsum        0
expense_ratio      0
fund_size_cr       0
fund_age_yr        0
sortino           21
alpha            144
sd                 0
beta              15
sharpe            20
risk_level         0
rating             0
returns_1yr      127
returns_3yr        0
returns_5yr        3
dtype: int64

In [40]:
df.loc[
    df['beta'].abs() > 5,
    ['scheme_name', 'category', 'sub_category',
     'beta', 'sd', 'sharpe', 'sortino',
     'alpha', 'returns_1yr', 'returns_3yr', 'returns_5yr']
]

,scheme_name,category,sub_category,beta,sd,sharpe,sortino,alpha,returns_1yr,returns_3yr,returns_5yr
85,Bandhan FTP – Sr.179,Debt,Fixed Maturity Plans,5.40,3.98,0.64,0.90,9.78,4.4,6.2,NaN
89,Bank of India Credit Risk Fund,Debt,Credit Risk Funds,-31.86,77.72,0.38,0.91,-13.36,130.8,12.8,-4.1
324,ICICI Pru Long Term Equity Fund,Equity,ELSS Mutual Funds,5.04,4.06,0.04,0.06,6.90,-0.2,27.1,11.5
632,SBI FMP – Series 1 (3668 Days) – Direct Growth,Debt,Fixed Maturity Plans,5.09,3.62,0.69,1.00,9.30,4.8,6.2,NaN

In [41]:
df.loc[
    df['returns_1yr'].abs() > 50,
    ['scheme_name', 'category', 'sub_category',
     'returns_1yr', 'returns_3yr', 'returns_5yr',
     'risk_level', 'sd', 'beta', 'sharpe']
]

,scheme_name,category,sub_category,returns_1yr,returns_3yr,returns_5yr,risk_level,sd,beta,sharpe
89,Bank of India Credit Risk Fund,Debt,Credit Risk Funds,130.8,12.8,-4.1,4,77.72,-31.86,0.38

In [42]:
df.loc[
    df['sd'] > 30,
    ['scheme_name', 'category', 'sub_category',
     'sd', 'returns_1yr', 'returns_3yr',
     'returns_5yr', 'beta', 'sharpe']
]

,scheme_name,category,sub_category,sd,returns_1yr,returns_3yr,returns_5yr,beta,sharpe
89,Bank of India Credit Risk Fund,Debt,Credit Risk Funds,77.72,130.8,12.8,-4.1,-31.86,0.38
177,DSP World Gold Fund,Other,FoFs Overseas,36.51,-9.0,14.8,10.2,NaN,0.40

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 814 entries, 0 to 813
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   scheme_name    814 non-null    object
 1   min_sip        814 non-null    int64
 2   min_lumpsum    814 non-null    int64
 3   expense_ratio  814 non-null    float64
 4   fund_size_cr   814 non-null    float64
 5   fund_age_yr    814 non-null    int64
 6   fund_manager   814 non-null    object
 7   sortino        791 non-null    float64
 8   alpha          772 non-null    float64
 9   sd             790 non-null    float64
 10  beta           772 non-null    float64
 11  sharpe         791 non-null    float64
 12  risk_level     814 non-null    int64
 13  amc_name       814 non-null    object
 14  rating         814 non-null    int64
 15  category       814 non-null    object
 16  sub_category   814 non-null    object
 17  returns_1yr    814 non-null    float64
 18  returns_3yr    793 non-null    float64
 19  returns_5yr    647 non-null    float64
dtypes: float64(10), int64(5), object(5)
memory usage: 127.3+ KB

In [44]:
df.isnull().sum()

scheme_name        0
min_sip            0
min_lumpsum        0
expense_ratio      0
fund_size_cr       0
fund_age_yr        0
fund_manager       0
sortino           23
alpha             42
sd                24
beta              42
sharpe            23
risk_level         0
amc_name           0
rating             0
category           0
sub_category       0
returns_1yr        0
returns_3yr       21
returns_5yr      167
dtype: int64

In [45]:
df.duplicated().sum()

np.int64(0)

## 6. Data Cleaning

In [39]:
#   remove unnecessary columns
#   convert data types
#   standardize numeric fields
#   check outliers

## 7. Exploratory Data Analysis

## 8. Risk vs Return Analysis

## 9. Fund Scoring / Ranking

## 10. Top 30 Funds

## 11. Key Insights

## 12. Export Clean Dataset