# Mutual Fund Overview & Insights



**Objective:** Analyze mutual fund schemes to identify funds with a strong balance between return, risk, and cost, and prepare the data for the later scoring, Top 30 selection, Excel output, and Power BI dashboard.

## 1. Project Objective

The goal of this project is to analyze mutual fund schemes and identify funds that provide a suitable balance between returns, risk, and cost. The final analysis is intended to help everyday investors compare mutual funds using measurable characteristics rather than looking only at the highest return.

The workflow uses Python for data cleaning and analysis, Excel for organizing the final Top 30 output, and Power BI for presenting the findings through an interactive dashboard.

### Project objectives
1. Clean and validate the raw mutual fund dataset.
2. Analyze fund returns, risk, costs, age, categories, ratings, and other relevant characteristics.
3. Normalize selected metrics and develop a transparent scoring methodology.
4. Rank the funds and identify the Top 30 schemes.
5. Present the findings through Excel and an interactive Power BI dashboard.

## 2. Import Libraries

In [1]:



import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## 3. Load Dataset

In [2]:
# Load the raw dataset

df = pd.read_csv("comprehensive_mutual_funds_data.csv")

print("Dataset loaded successfully.")

Dataset loaded successfully.

In [3]:
# Display the first five records
df.head()

,scheme_name,min_sip,min_lumpsum,expense_ratio,fund_size_cr,fund_age_yr,fund_manager,sortino,alpha,sd,beta,sharpe,risk_level,amc_name,rating,category,sub_category,returns_1yr,returns_3yr,returns_5yr
0,Aditya Birla SL Active Debt Multi-Mgr FoF-Dir ...,100,100,0.27,10.0,10,Kaustubh Gupta,0.32,2.24,9.39,0.01,0.24,3,Aditya Birla Sun Life Mutual Fund,3,Other,FoFs Domestic,4.0,6.5,6.9
1,Aditya Birla SL Arbitrage Fund,1000,1000,0.36,4288.0,10,Lovelish Solanki,1.33,1.53,0.72,0.56,1.1,1,Aditya Birla Sun Life Mutual Fund,3,Hybrid,Arbitrage Mutual Funds,5.6,4.8,5.5
2,Aditya Birla SL Asset Allocator FoF-Dir Growth,1000,1000,0.53,157.0,10,Vinod Narayan Bhat,3.44,2.67,10.58,0.67,1.42,5,Aditya Birla Sun Life Mutual Fund,3,Other,FoFs Domestic,2.0,18.9,9.7
3,Aditya Birla SL Bal Bhavishya Yojna – Dir Growth,500,1000,0.76,637.0,4,Atul Penkar,2.18,-6.37,14.99,0.85,0.9,6,Aditya Birla Sun Life Mutual Fund,2,Solution Oriented,Childrens Funds,-0.7,17.1,NaN
4,Aditya Birla SL Balanced Advantage Fund,100,100,0.61,6386.0,10,Mohit Sharma,3.69,1.99,10.38,0.68,1.39,6,Aditya Birla Sun Life Mutual Fund,4,Hybrid,Dynamic Asset Allocation or Balanced Advantage,4.5,18.6,9.7

## 4. Initial Data Inspection

In [4]:
# Dataset dimensions
rows, columns = df.shape

print("Number of rows:", rows)
print("Number of columns:", columns)

Number of rows: 814
Number of columns: 20

In [6]:
# Column names

df.columns

Index(['scheme_name', 'min_sip', 'min_lumpsum', 'expense_ratio',
       'fund_size_cr', 'fund_age_yr', 'fund_manager', 'sortino', 'alpha', 'sd',
       'beta', 'sharpe', 'risk_level', 'amc_name', 'rating', 'category',
       'sub_category', 'returns_1yr', 'returns_3yr', 'returns_5yr'],
      dtype='object')

In [7]:
# Last five records
df.tail()

,scheme_name,min_sip,min_lumpsum,expense_ratio,fund_size_cr,fund_age_yr,fund_manager,sortino,alpha,sd,beta,sharpe,risk_level,amc_name,rating,category,sub_category,returns_1yr,returns_3yr,returns_5yr
809,UTI-Unit Linked Insurance Plan – Direct,500,15000,0.96,5068.0,10,Amandeep Chopra,2.47,0.92,7.06,0.44,1.29,4,UTI Mutual Fund,0,Hybrid,Dynamic Asset Allocation or Balanced Advantage,-0.7,13.1,6.2
810,UTI-Value Opportunities Fund,500,5000,1.16,6740.0,10,Vetri Subramaniam,3.21,2.73,15.62,0.9,1.48,6,UTI Mutual Fund,4,Equity,Value Funds,1.7,27.2,12.2
811,WhiteOak Capital Liquid Fund,500,500,0.26,197.0,4,Piyush Baranwal,-0.42,0.93,0.39,0.72,-0.07,1,WhiteOak Capital Mutual Fund,1,Debt,Liquid Mutual Funds,5.3,3.8,NaN
812,WhiteOak Capital Overnight Fund,500,500,0.22,14.0,4,Piyush Baranwal,-0.42,0.93,0.39,0.72,-0.07,1,WhiteOak Capital Mutual Fund,1,Debt,Overnight Mutual Funds,1.7,32.4,13.3
813,WhiteOak Capital Ultra Short Term Fund,500,500,0.33,141.0,4,Piyush Baranwal,2.81,1.2,0.72,0.47,0.8,1,WhiteOak Capital Mutual Fund,2,Debt,Ultra Short Duration Funds,5.3,4.5,NaN

In [8]:
# Data types and non-null counts
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 814 entries, 0 to 813
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   scheme_name    814 non-null    object
 1   min_sip        814 non-null    int64
 2   min_lumpsum    814 non-null    int64
 3   expense_ratio  814 non-null    float64
 4   fund_size_cr   814 non-null    float64
 5   fund_age_yr    814 non-null    int64
 6   fund_manager   814 non-null    object
 7   sortino        814 non-null    object
 8   alpha          814 non-null    object
 9   sd             814 non-null    object
 10  beta           814 non-null    object
 11  sharpe         814 non-null    object
 12  risk_level     814 non-null    int64
 13  amc_name       814 non-null    object
 14  rating         814 non-null    int64
 15  category       814 non-null    object
 16  sub_category   814 non-null    object
 17  returns_1yr    814 non-null    float64
 18  returns_3yr    793 non-null    float64
 19  returns_5yr    647 non-null    float64
dtypes: float64(5), int64(5), object(10)
memory usage: 127.3+ KB

In [9]:
# Statistical overview of numeric columns
df.describe()

,min_sip,min_lumpsum,expense_ratio,fund_size_cr,fund_age_yr,risk_level,rating,returns_1yr,returns_3yr,returns_5yr
count,814.000000,814.000000,814.000000,814.000000,814.000000,814.000000,814.000000,814.000000,793.000000,647.000000
mean,528.500000,3047.468059,0.713231,3812.854214,8.319410,4.400491,2.641278,3.921376,18.525347,9.490726
std,369.184517,2514.619513,0.482161,7181.479475,2.640622,1.814741,1.463476,6.675502,12.108476,3.714015
min,0.000000,0.000000,0.000000,2.380000,1.000000,1.000000,0.000000,-19.700000,3.300000,-4.100000
25%,150.000000,500.000000,0.310000,175.250000,6.000000,3.000000,2.000000,1.500000,6.200000,6.700000
50%,500.000000,5000.000000,0.615000,940.500000,10.000000,6.000000,3.000000,4.400000,18.500000,8.900000
75%,1000.000000,5000.000000,1.030000,3819.000000,10.000000,6.000000,4.000000,5.600000,27.100000,12.200000
max,2000.000000,25000.000000,2.590000,57052.000000,17.000000,6.000000,5.000000,130.800000,71.400000,23.200000

### Key column groups

- **Fund identification:** `scheme_name`, `fund_manager`, `amc_name`
- **Investment requirements and fund characteristics:** `min_sip`, `min_lumpsum`, `expense_ratio`, `fund_size_cr`, `fund_age_yr`
- **Risk and risk-adjusted performance:** `sortino`, `alpha`, `sd`, `beta`, `sharpe`, `risk_level`
- **Classification and rating:** `rating`, `category`, `sub_category`
- **Historical returns:** `returns_1yr`, `returns_3yr`, `returns_5yr`

## 5. Data Cleaning

### 5.1 Missing Value Analysis

In [ ]:
# Count missing values
missing_count = df.isnull().sum()
missing_percentage = (missing_count / len(df)) * 100

missing_summary = pd.DataFrame({
    'Missing Values': missing_count,
    'Missing Percentage': missing_percentage
})

missing_summary[missing_summary['Missing Values'] > 0].sort_values(
    'Missing Values', ascending=False
)

             Missing Values  Missing Percentage
returns_5yr             167           20.515971
returns_3yr              21            2.579853

In [ ]:
# Investigate missing 3-year and 5-year returns
df[df['returns_3yr'].isnull()][
    ['scheme_name', 'fund_age_yr', 'category', 'sub_category',
     'returns_1yr', 'returns_3yr', 'returns_5yr']
].head(20)

,scheme_name,fund_age_yr,category,sub_category,returns_1yr,returns_3yr,returns_5yr
61,AXIS Floater Fund,2,Debt,Floater Mutual Funds,5.8,NaN,NaN
104,Baroda BNP Paribas Banking & PSU Bond Fund,2,Debt,Banking and PSU Mutual Funds,2.5,NaN,NaN
125,BHARAT Bond FOF – April 2025 – Direct Growth,3,Other,FoFs Domestic,2.6,NaN,NaN
154,DSP Floater Fund,2,Debt,Floater Mutual Funds,4.4,NaN,NaN
398,Invesco India Medium Duration Fund,2,Debt,Medium Duration Funds,3.5,NaN,NaN
411,ITI Banking & PSU Debt Fund,2,Debt,Banking and PSU Mutual Funds,5.4,NaN,NaN
412,ITI Dynamic Bond Fund,2,Debt,Dynamic Bond,5.7,NaN,NaN
417,ITI Ultra Short Duration Fund,2,Debt,Ultra Short Duration Funds,5.3,NaN,NaN
495,Mahindra Manulife Short Duration Fund,2,Debt,Short Duration Funds,4.4,NaN,NaN
497,Mirae Asset Banking and PSU Debt Fund,3,Debt,Banking and PSU Mutual Funds,3.7,NaN,NaN
499,Mirae Asset Corporate Bond Fund,2,Debt,Corporate Bond Mutual Funds,3.7,NaN,NaN
509,Mirae Asset Money Market Fund,2,Debt,Money Market Funds,5.3,NaN,NaN
514,Mirae Asset Ultra Short Duration Fund,2,Debt,Ultra Short Duration Funds,5.5,NaN,NaN
631,SBI Floating Rate Debt Fund,2,Debt,Floater Mutual Funds,5.0,NaN,NaN
689,Sundaram Large Cap Fund,2,Equity,Large Cap Mutual Funds,0.9,NaN,NaN
720,Tata Floating Rate Fund,2,Debt,Floater Mutual Funds,5.6,NaN,NaN
755,TRUSTMF Banking & PSU Debt Fund,2,Debt,Banking and PSU Mutual Funds,3.0,NaN,NaN
756,TRUSTMF Liquid Fund,2,Debt,Liquid Mutual Funds,5.6,NaN,NaN
757,TRUSTMF Short Term Fund,2,Debt,Short Duration Funds,4.2,NaN,NaN
769,Union Medium Duration Fund,3,Debt,Medium Duration Funds,2.3,NaN,NaN

In [ ]:
df[df['returns_5yr'].isnull()][
    ['scheme_name', 'fund_age_yr', 'category', 'sub_category',
     'returns_1yr', 'returns_3yr', 'returns_5yr']
].head(20)

,scheme_name,fund_age_yr,category,sub_category,returns_1yr,returns_3yr,returns_5yr
3,Aditya Birla SL Bal Bhavishya Yojna – Dir Growth,4,Solution Oriented,Childrens Funds,-0.7,17.1,NaN
38,Aditya Birla SL Overnight Fund,4,Debt,Overnight Mutual Funds,5.4,3.9,NaN
41,Aditya Birla SL Retirement-The 30s Plan-Dir Gr...,4,Solution Oriented,Retirement Funds,0.0,17.9,NaN
42,Aditya Birla SL Retirement-The 40s Plan-Dir Gr...,4,Solution Oriented,Retirement Funds,-0.1,15.0,NaN
43,Aditya Birla SL Retirement-The 50s Plan-Dir Gr...,4,Solution Oriented,Retirement Funds,3.0,4.6,NaN
44,Aditya Birla SL Retirement-The 50sPlus-Debt-Di...,4,Solution Oriented,Retirement Funds,2.9,4.6,NaN
49,AXIS All Seasons Debt Fund,3,Other,FoFs Domestic,4.7,6.2,NaN
58,AXIS Equity Hybrid Fund,5,Hybrid,Aggressive Hybrid Mutual Funds,-4.9,17.4,NaN
61,AXIS Floater Fund,2,Debt,Floater Mutual Funds,5.8,NaN,NaN
67,AXIS Growth Opportunities Fund,4,Equity,Large & Mid Cap Funds,-6.4,26.5,NaN
71,AXIS Money Market Fund,4,Debt,Money Market Funds,5.6,5.4,NaN
72,AXIS Nifty 100 Index Fund,3,Other,Index Funds,-1.7,25.1,NaN
73,AXIS Overnight Fund,4,Debt,Overnight Mutual Funds,5.4,3.9,NaN
75,AXIS Retirement Savings Fund,3,Solution Oriented,Retirement Funds,-1.3,13.6,NaN
76,AXIS Retirement Savings Fund,3,Solution Oriented,Retirement Funds,-2.5,10.3,NaN
77,AXIS Retirement Savings Fund,3,Solution Oriented,Retirement Funds,-4.1,14.0,NaN
83,AXIS Ultra Short Term Fund,5,Debt,Ultra Short Duration Funds,5.7,5.4,NaN
85,Bandhan FTP – Sr.179,4,Debt,Fixed Maturity Plans,4.4,6.2,NaN
86,Bank of India Arbitrage Fund,5,Hybrid,Arbitrage Mutual Funds,4.2,3.4,NaN
95,Bank of India Midcap Tax Fund,4,Equity,ELSS Mutual Funds,-4.7,26.0,NaN

In [ ]:
# Missing 5-year returns by fund age
df[df['returns_5yr'].isnull()]['fund_age_yr'].value_counts().sort_index()

fund_age_yr
2    18
3    27
4    86
5    36
Name: count, dtype: int64

**Missing-value treatment decision:** Missing historical return values are retained as `NaN` rather than being replaced with zero, because a missing return does not mean that the fund earned 0%. Similarly, unavailable risk/performance metrics are retained as missing values and will be handled explicitly during later ranking and analysis.

### 5.2 Duplicate Check

In [ ]:
duplicate_counts = df.duplicated().sum()

print("Number of duplicates : ", duplicate_counts)

Number of duplicates :  0

### 5.3 Data Type Check

In [14]:
# Check the data type of every column
df.dtypes

scheme_name       object
min_sip            int64
min_lumpsum        int64
expense_ratio    float64
fund_size_cr     float64
fund_age_yr        int64
fund_manager      object
sortino           object
alpha             object
sd                object
beta              object
sharpe            object
risk_level         int64
amc_name          object
rating             int64
category          object
sub_category      object
returns_1yr      float64
returns_3yr      float64
returns_5yr      float64
dtype: object

- **Performance Metrices :** `sortino`, `alpha`, `sd`, `beta`, `sharpe`

In [15]:
# Performance metrics expected to be numeric
performance_cols = ['sortino', 'alpha', 'sd', 'beta', 'sharpe']

for col in performance_cols:
    print(f"\n{col}")
    print("Sample values:", df[col].unique()[:20])

sortino
Sample values: ['0.32' '1.33' '3.44' '2.18' '3.69' '2.07' '1.92' '1.42' '2.28' '1.82'
 '2.42' '3.78' '1.78' '2.21' '2.54' '2.55' '3.4' '2.81' '3.24' '3.13']

alpha
Sample values: ['2.24' '1.53' '2.67' '-6.37' '1.99' '1.24' '4.46' '-' '2.38' '3.01'
 '9.37' '5.04' '3.02' '-2.06' '1.43' '1.11' '-1.46' '3.73' '-1.14' '1.65']

sd
Sample values: ['9.39' '0.72' '10.58' '14.99' '10.38' '25.53' '1.91' '20.18' '1.93' '2.9'
 '21.12' '15.77' '3.22' '17.61' '12.84' '6.83' '16.6' '1.14' '16.09'
 '11.73']

beta
Sample values: ['0.01' '0.56' '0.67' '0.85' '0.68' '0.96' '1.78' '-' '0.78' '-0.95'
 '0.83' '0.91' '0.98' '0.99' '1.37' '0.95' '0.8' '0.36' '0.58' '0.97']

sharpe
Sample values: ['0.24' '1.1' '1.42' '0.9' '1.39' '0.97' '1.09' '1.06' '1.35' '1.47'
 '1.53' '1.58' '1.02' '1.16' '1.33' '1.2' '1.27' '1.66' '1.26' '1.4']

In [16]:
# Count values that cannot be converted to numeric
for col in performance_cols:
    numeric_values = pd.to_numeric(df[col], errors='coerce')
    print(col, "-> Non-numeric values:", numeric_values.isna().sum())

sortino -> Non-numeric values: 23
alpha -> Non-numeric values: 42
sd -> Non-numeric values: 24
beta -> Non-numeric values: 42
sharpe -> Non-numeric values: 23

### 5.4 Numeric Standardization

The performance metric columns were stored as text even though most values were numeric. The source data also contains `'-'` in these fields. The `'-'` values are treated as unavailable (`NaN`) rather than as zero, and the columns are then converted to numeric types.

In [17]:
# Replace unavailable '-' values with NaN and convert performance metrics to numeric
for col in performance_cols:
    df[col] = df[col].replace('-', np.nan)
    df[col] = pd.to_numeric(df[col], errors='coerce')

df[performance_cols].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 814 entries, 0 to 813
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   sortino  791 non-null    float64
 1   alpha    772 non-null    float64
 2   sd       790 non-null    float64
 3   beta     772 non-null    float64
 4   sharpe   791 non-null    float64
dtypes: float64(5)
memory usage: 31.9 KB

In [18]:
# Verify missing values created by the unavailable '-' entries
df[performance_cols].isnull().sum()

sortino    23
alpha      42
sd         24
beta       42
sharpe     23
dtype: int64

### 5.5 Categorical Consistency

In [19]:
# Check category values
print("Category values:")
print(df['category'].value_counts())

print("\nSub-category values:")
print(df['sub_category'].value_counts())

print("\nRisk levels:")
print(df['risk_level'].value_counts().sort_index())

print("\nRatings:")
print(df['rating'].value_counts().sort_index())

Category values:
category
Equity               308
Debt                 282
Hybrid               116
Other                 80
Solution Oriented     28
Name: count, dtype: int64

Sub-category values:
sub_category
Sectoral / Thematic Mutual Funds                  82
ELSS Mutual Funds                                 52
FoFs Domestic                                     35
Liquid Mutual Funds                               34
Index Funds                                       30
Aggressive Hybrid Mutual Funds                    30
Large Cap Mutual Funds                            28
Overnight Mutual Funds                            26
Small Cap Mutual Funds                            25
Ultra Short Duration Funds                        25
Large & Mid Cap Funds                             24
Mid Cap Mutual Funds                              23
Short Duration Funds                              23
Arbitrage Mutual Funds                            22
Flexi Cap Funds                                   22
Dynamic Bond                                      22
Banking and PSU Mutual Funds                      21
Equity Savings Mutual Funds                       21
Low Duration Funds                                20
Focused Funds                                     20
Retirement Funds                                  20
Gilt Mutual Funds                                 19
Money Market Funds                                19
Corporate Bond Mutual Funds                       19
Dynamic Asset Allocation or Balanced Advantage    19
Conservative Hybrid Mutual Funds                  17
FoFs Overseas                                     15
Medium Duration Funds                             14
Credit Risk Funds                                 14
Value Funds                                       13
Medium to Long Duration Funds                     11
Floater Mutual Funds                              11
Multi Cap Funds                                   10
Childrens Funds                                    8
Multi Asset Allocation Mutual Funds                7
Dividend Yield Funds                               6
Fixed Maturity Plans                               4
Contra Funds                                       3
Name: count, dtype: int64

Risk levels:
risk_level
1     53
2    127
3    124
4     65
5     27
6    418
Name: count, dtype: int64

Ratings:
rating
0    108
1     58
2    168
3    243
4    158
5     79
Name: count, dtype: int64

The categorical checks are used to identify unexpected spelling/case variations or invalid ranges. The observed values are retained because they are consistent with the supplied dataset.

### 5.6 Outlier Investigation

Outliers are investigated rather than automatically deleted. An unusually high or low financial metric is not necessarily a data error. Values are retained unless there is evidence that they are incorrect.

In [20]:
numeric_cols = [
    'min_sip', 'min_lumpsum', 'expense_ratio', 'fund_size_cr', 'fund_age_yr',
    'sortino', 'alpha', 'sd', 'beta', 'sharpe', 'risk_level', 'rating',
    'returns_1yr', 'returns_3yr', 'returns_5yr'
]

# Minimum and maximum values
df[numeric_cols].agg(['min', 'max']).T

                 min       max
min_sip         0.00   2000.00
min_lumpsum     0.00  25000.00
expense_ratio   0.00      2.59
fund_size_cr    2.38  57052.00
fund_age_yr     1.00     17.00
sortino        -1.77     12.57
alpha         -13.36     27.24
sd              0.27     77.72
beta          -31.86      5.40
sharpe         -0.82      3.52
risk_level      1.00      6.00
rating          0.00      5.00
returns_1yr   -19.70    130.80
returns_3yr     3.30     71.40
returns_5yr    -4.10     23.20

In [21]:
# Count negative values
df[numeric_cols].lt(0).sum()

min_sip            0
min_lumpsum        0
expense_ratio      0
fund_size_cr       0
fund_age_yr        0
sortino           21
alpha            144
sd                 0
beta              15
sharpe            20
risk_level         0
rating             0
returns_1yr      127
returns_3yr        0
returns_5yr        3
dtype: int64

In [22]:
# Investigate unusually large absolute beta values
df.loc[
    df['beta'].abs() > 5,
    ['scheme_name', 'category', 'sub_category', 'beta', 'sd', 'sharpe',
     'sortino', 'alpha', 'returns_1yr', 'returns_3yr', 'returns_5yr']
]

,scheme_name,category,sub_category,beta,sd,sharpe,sortino,alpha,returns_1yr,returns_3yr,returns_5yr
85,Bandhan FTP – Sr.179,Debt,Fixed Maturity Plans,5.40,3.98,0.64,0.90,9.78,4.4,6.2,NaN
89,Bank of India Credit Risk Fund,Debt,Credit Risk Funds,-31.86,77.72,0.38,0.91,-13.36,130.8,12.8,-4.1
324,ICICI Pru Long Term Equity Fund,Equity,ELSS Mutual Funds,5.04,4.06,0.04,0.06,6.90,-0.2,27.1,11.5
632,SBI FMP – Series 1 (3668 Days) – Direct Growth,Debt,Fixed Maturity Plans,5.09,3.62,0.69,1.00,9.30,4.8,6.2,NaN

In [23]:
# Investigate unusually large absolute 1-year returns
df.loc[
    df['returns_1yr'].abs() > 50,
    ['scheme_name', 'category', 'sub_category', 'returns_1yr',
     'returns_3yr', 'returns_5yr', 'risk_level', 'sd', 'beta', 'sharpe']
]

,scheme_name,category,sub_category,returns_1yr,returns_3yr,returns_5yr,risk_level,sd,beta,sharpe
89,Bank of India Credit Risk Fund,Debt,Credit Risk Funds,130.8,12.8,-4.1,4,77.72,-31.86,0.38

In [24]:
# Investigate unusually high standard deviation
df.loc[
    df['sd'] > 30,
    ['scheme_name', 'category', 'sub_category', 'sd',
     'returns_1yr', 'returns_3yr', 'returns_5yr', 'beta', 'sharpe']
]

,scheme_name,category,sub_category,sd,returns_1yr,returns_3yr,returns_5yr,beta,sharpe
89,Bank of India Credit Risk Fund,Debt,Credit Risk Funds,77.72,130.8,12.8,-4.1,-31.86,0.38
177,DSP World Gold Fund,Other,FoFs Overseas,36.51,-9.0,14.8,10.2,NaN,0.40

**Outlier decision:** The extreme observations identified above are retained. The analysis found no evidence from the supplied data alone that these observations are data-entry errors. They will be considered during interpretation and later scoring rather than being arbitrarily removed.

### 5.7 Missing Value Treatment

#### Treatment decisions

- `returns_3yr` and `returns_5yr`: retain missing values as `NaN` because unavailable historical periods should not be treated as 0% return.
- `sortino`, `alpha`, `sd`, `beta`, and `sharpe`: retain `NaN` where the original dataset contained `'-'`, because unavailable metrics should not be converted to zero.
- No blanket `fillna(0)` operation is used.
- Records are retained so useful information in other columns is not unnecessarily discarded.

In [25]:
# Review all remaining missing values after cleaning
df.isnull().sum().sort_values(ascending=False)

returns_5yr      167
alpha             42
beta              42
sd                24
sharpe            23
sortino           23
returns_3yr       21
amc_name           0
returns_1yr        0
sub_category       0
category           0
rating             0
expense_ratio      0
risk_level         0
fund_size_cr       0
min_sip            0
min_lumpsum        0
fund_manager       0
fund_age_yr        0
scheme_name        0
dtype: int64

### 5.8 Final Validation

In [26]:
# Final data structure check
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 814 entries, 0 to 813
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   scheme_name    814 non-null    object
 1   min_sip        814 non-null    int64
 2   min_lumpsum    814 non-null    int64
 3   expense_ratio  814 non-null    float64
 4   fund_size_cr   814 non-null    float64
 5   fund_age_yr    814 non-null    int64
 6   fund_manager   814 non-null    object
 7   sortino        791 non-null    float64
 8   alpha          772 non-null    float64
 9   sd             790 non-null    float64
 10  beta           772 non-null    float64
 11  sharpe         791 non-null    float64
 12  risk_level     814 non-null    int64
 13  amc_name       814 non-null    object
 14  rating         814 non-null    int64
 15  category       814 non-null    object
 16  sub_category   814 non-null    object
 17  returns_1yr    814 non-null    float64
 18  returns_3yr    793 non-null    float64
 19  returns_5yr    647 non-null    float64
dtypes: float64(10), int64(5), object(5)
memory usage: 127.3+ KB

In [27]:
# Final missing-value check
df.isnull().sum()

scheme_name        0
min_sip            0
min_lumpsum        0
expense_ratio      0
fund_size_cr       0
fund_age_yr        0
fund_manager       0
sortino           23
alpha             42
sd                24
beta              42
sharpe            23
risk_level         0
amc_name           0
rating             0
category           0
sub_category       0
returns_1yr        0
returns_3yr       21
returns_5yr      167
dtype: int64

In [28]:
# Final duplicate check
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [29]:
# Confirm the performance metrics are numeric
print(df[performance_cols].dtypes)

sortino    float64
alpha      float64
sd         float64
beta       float64
sharpe     float64
dtype: object

## 6. Cleaned Dataset

The cleaned dataset is stored in a separate DataFrame so that the original raw file remains unchanged.

In [30]:
# Create a separate cleaned-data copy
clean_df = df.copy()

print("Cleaned dataset shape:", clean_df.shape)
clean_df.head()

Cleaned dataset shape: (814, 20)

,scheme_name,min_sip,min_lumpsum,expense_ratio,fund_size_cr,fund_age_yr,fund_manager,sortino,alpha,sd,beta,sharpe,risk_level,amc_name,rating,category,sub_category,returns_1yr,returns_3yr,returns_5yr
0,Aditya Birla SL Active Debt Multi-Mgr FoF-Dir ...,100,100,0.27,10.0,10,Kaustubh Gupta,0.32,2.24,9.39,0.01,0.24,3,Aditya Birla Sun Life Mutual Fund,3,Other,FoFs Domestic,4.0,6.5,6.9
1,Aditya Birla SL Arbitrage Fund,1000,1000,0.36,4288.0,10,Lovelish Solanki,1.33,1.53,0.72,0.56,1.10,1,Aditya Birla Sun Life Mutual Fund,3,Hybrid,Arbitrage Mutual Funds,5.6,4.8,5.5
2,Aditya Birla SL Asset Allocator FoF-Dir Growth,1000,1000,0.53,157.0,10,Vinod Narayan Bhat,3.44,2.67,10.58,0.67,1.42,5,Aditya Birla Sun Life Mutual Fund,3,Other,FoFs Domestic,2.0,18.9,9.7
3,Aditya Birla SL Bal Bhavishya Yojna – Dir Growth,500,1000,0.76,637.0,4,Atul Penkar,2.18,-6.37,14.99,0.85,0.90,6,Aditya Birla Sun Life Mutual Fund,2,Solution Oriented,Childrens Funds,-0.7,17.1,NaN
4,Aditya Birla SL Balanced Advantage Fund,100,100,0.61,6386.0,10,Mohit Sharma,3.69,1.99,10.38,0.68,1.39,6,Aditya Birla Sun Life Mutual Fund,4,Hybrid,Dynamic Asset Allocation or Balanced Advantage,4.5,18.6,9.7

In [31]:
# Export cleaned dataset without the DataFrame index
clean_df.to_csv('mutual_funds_cleaned.csv', index=False)

print("Cleaned dataset exported as: mutual_funds_cleaned.csv")

Cleaned dataset exported as: mutual_funds_cleaned.csv

# Stage 2: Data Description & Understanding

## 2.1 Statistical Summary

In [32]:
main_numeric_cols = [
    'min_sip',
    'min_lumpsum',
    'expense_ratio',
    'fund_size_cr',
    'fund_age_yr',
    'sortino',
    'alpha',
    'sd',
    'beta',
    'sharpe',
    'risk_level',
    'rating',
    'returns_1yr',
    'returns_3yr',
    'returns_5yr'
]

These are the main numerical variables relevant to understanding the funds.

# Summary

In [ ]:
summary = pd.DataFrame({
    'Mean': df[main_numeric_cols].mean(),
    'Median': df[main_numeric_cols].median(),
    'Mode': df[main_numeric_cols].mode().iloc[0],
    'Minimum': df[main_numeric_cols].min(),
    'Maximum': df[main_numeric_cols].max(),
    'Std Dev': df[main_numeric_cols].std()
})

summary

                      Mean    Median     Mode  Minimum   Maximum      Std Dev
min_sip         528.500000   500.000   500.00     0.00   2000.00   369.184517
min_lumpsum    3047.468059  5000.000  5000.00     0.00  25000.00  2514.619513
expense_ratio     0.713231     0.615     0.21     0.00      2.59     0.482161
fund_size_cr   3812.854214   940.500    90.00     2.38  57052.00  7181.479475
fund_age_yr       8.319410    10.000    10.00     1.00     17.00     2.640622
sortino           2.652642     2.870     3.24    -1.77     12.57     1.392228
alpha             2.505635     1.855     0.67   -13.36     27.24     3.951573
sd               10.272696    12.300     0.38     0.27     77.72     7.805667
beta              0.822241     0.860     0.94   -31.86      5.40     1.309871
sharpe            1.204185     1.290     1.40    -0.82      3.52     0.536431
risk_level        4.400491     6.000     6.00     1.00      6.00     1.814741
rating            2.641278     3.000     3.00     0.00      5.00     1.463476
returns_1yr       3.921376     4.400     5.60   -19.70    130.80     6.675502
returns_3yr      18.525347    18.500     3.90     3.30     71.40    12.108476
returns_5yr       9.490726     8.900     5.30    -4.10     23.20     3.714015

In [34]:
summary_rounded = summary.round(2)

summary_rounded

                  Mean   Median     Mode  Minimum   Maximum  Std Dev
min_sip         528.50   500.00   500.00     0.00   2000.00   369.18
min_lumpsum    3047.47  5000.00  5000.00     0.00  25000.00  2514.62
expense_ratio     0.71     0.62     0.21     0.00      2.59     0.48
fund_size_cr   3812.85   940.50    90.00     2.38  57052.00  7181.48
fund_age_yr       8.32    10.00    10.00     1.00     17.00     2.64
sortino           2.65     2.87     3.24    -1.77     12.57     1.39
alpha             2.51     1.86     0.67   -13.36     27.24     3.95
sd               10.27    12.30     0.38     0.27     77.72     7.81
beta              0.82     0.86     0.94   -31.86      5.40     1.31
sharpe            1.20     1.29     1.40    -0.82      3.52     0.54
risk_level        4.40     6.00     6.00     1.00      6.00     1.81
rating            2.64     3.00     3.00     0.00      5.00     1.46
returns_1yr       3.92     4.40     5.60   -19.70    130.80     6.68
returns_3yr      18.53    18.50     3.90     3.30     71.40    12.11
returns_5yr       9.49     8.90     5.30    -4.10     23.20     3.71

What do these statistics tell you about the typical fund?

In [ ]:
# comparison between mean and median

comparison = pd.DataFrame({
    'Mean': df[main_numeric_cols].mean(),
    'Median': df[main_numeric_cols].median()
})

comparison['Mean - Median'] = (
    comparison['Mean'] - comparison['Median']
)

comparison.round(2)

                  Mean   Median  Mean - Median
min_sip         528.50   500.00          28.50
min_lumpsum    3047.47  5000.00       -1952.53
expense_ratio     0.71     0.62           0.10
fund_size_cr   3812.85   940.50        2872.35
fund_age_yr       8.32    10.00          -1.68
sortino           2.65     2.87          -0.22
alpha             2.51     1.86           0.65
sd               10.27    12.30          -2.03
beta              0.82     0.86          -0.04
sharpe            1.20     1.29          -0.09
risk_level        4.40     6.00          -1.60
rating            2.64     3.00          -0.36
returns_1yr       3.92     4.40          -0.48
returns_3yr      18.53    18.50           0.03
returns_5yr       9.49     8.90           0.59

### Mean vs Median Insights

The mean represents the average value, while the median represents the middle value. When they are close, the data is generally balanced. A large difference between them indicates that some unusually high or low values are affecting the average.

In this dataset, fund size has a much higher mean than median, showing that a few very large funds increase the average. For most return measures, the mean and median are relatively close, suggesting that the typical return is not heavily affected by extreme values.

In [36]:
returns_data = df[['returns_1yr', 'returns_3yr', 'returns_5yr']]

returns_data.to_excel(
    'mutual_fund_returns_for_boxplot.xlsx',
    index=False
)